import {createRequire} from 'node:module';
import {mkdirSync} from 'node:fs';
import assert from 'node:assert/strict';
const require=createRequire(import.meta.url),{build}=require(require.resolve('esbuild',{paths:[require.resolve('wrangler')]}));
mkdirSync('.runtime-tests',{recursive:true});
await build({stdin:{contents:"export {default as RecentTask} from './app/recent-task';export {default as EmployeeDay} from './app/employee-day';export {default as FocusDay} from './app/focus-day';export {notices,recordSchema,assistantItems,possibleDuplicates} from './lib/model';export {default as SpaceCards} from './app/space-cards';export {default as Assistant} from './app/assistant';export {default as Notifications} from './app/notifications';export {QuickTaskForm} from './app/quick-task';",resolveDir:process.cwd()},bundle:true,platform:'node',format:'cjs',jsx:'automatic',external:['react','react-dom','react-dom/server'],outfile:'.runtime-tests/dashboard.cjs'});
const {RecentTask,EmployeeDay,FocusDay,recordSchema,SpaceCards,QuickTaskForm,notices,assistantItems,possibleDuplicates,Assistant,Notifications}=require('../.runtime-tests/dashboard.cjs');
const React=require('react'),{renderToStaticMarkup}=require('react-dom/server');
const initial=recordSchema.parse({title:'Tarefa base',area:'Casa'});
const item=(id,title,patch={},kind='task')=>({id,kind,data:{...initial,title,...patch},version:1,updated_at:'2026-10-07T14:11:00Z',created_by:'ana@test.pt'});
const props={me:{name:'Ana',role:'admin'},today:'2026-10-07',initial,refresh:async()=>{},open:()=>{},create:()=>{},remove:()=>{},canRemove:()=>true};
// A saved task with no date or selected daily plan must be visible immediately.
const html=renderToStaticMarkup(React.createElement(FocusDay,{...props,items:[item('1','Ir às finanças',{assignee:'Afonso Marques',area:'Quinta · Arruda'}),item('2','Fechado',{status:'Concluído'}),item('3','Cancelado',{status:'Cancelado'}),item('4','Contacto',{},'supplier'),item('5','Aguardar orçamento',{status:'À espera',waitingFor:'Técnico'}),item('6','Adiado',{snoozeUntil:'2026-10-10'})]}));
assert.match(html,/Assuntos em aberto/);
assert.match(html,/Ir às finanças/);
assert.match(html,/Afonso Marques/);
assert.match(html,/Quinta · Arruda/);
assert.match(html,/Sem prazo/);
assert.match(html,/Aguardar orçamento/);
assert.match(html,/Adiado/);
assert.doesNotMatch(html,/>Fechado</);
assert.doesNotMatch(html,/>Cancelado</);
assert.doesNotMatch(html,/>Contacto</);
assert.doesNotMatch(html,/Outros assuntos/);
assert.match(html,/Filtrar assuntos por responsável/);
assert.match(html,/Filtrar assuntos por espaço/);
const empty=renderToStaticMarkup(React.createElement(FocusDay,{...props,items:[]}));
assert.match(empty,/Ainda não há assuntos em aberto/);
console.log('Dashboard regression passed: undated/unplanned tasks visible; waiting and snoozed tasks retained; closed records and contacts excluded.');

const cards=renderToStaticMarkup(React.createElement(SpaceCards,{items:[item('a','Ir às finanças',{area:'Quinta · Arruda'}),item('b','Limpar secador',{area:'Lavandaria',due:'2026-10-07'}),item('c','Encerrado',{area:'Lavandaria',status:'Concluído'})],admin:true,today:'2026-10-07',onOpen:()=>{},onAdd:()=>{}}));
assert.match(cards,/Adicionar tarefa em Quinta · Arruda/);
assert.match(cards,/Ir às finanças/);
assert.match(cards,/1 com prazo hoje ou ultrapassado/);
assert.equal((cards.match(/class="space-card space-card-/g)||[]).length,7);
const employeeCards=renderToStaticMarkup(React.createElement(SpaceCards,{items:[],admin:false,today:'2026-10-07',onOpen:()=>{},onAdd:()=>{}}));
assert.doesNotMatch(employeeCards,/Abrir Família/);
const quick=renderToStaticMarkup(React.createElement(QuickTaskForm,{draft:{...initial,title:'',area:'Lavandaria',assignee:'Ana'},team:[{name:'Ana'},{name:'Afonso Marques'}],admin:true,today:'2026-10-07',onClose:()=>{},onSaved:async()=>{},onDetails:()=>{}}));
assert.match(quick,/<option selected="">Lavandaria<\/option>/);
assert.match(quick,/<option selected="">Ana<\/option>/);
assert.match(quick,/Adicionar tarefa/);
assert.match(quick,/Hoje/);
assert.match(quick,/Amanhã/);
assert.match(quick,/Mais detalhes e fotografia/);
assert.doesNotMatch(quick,/Custo da intervenção/);
console.log('Space cards and short task form passed: context retained, real counters, role limits and optional details.');

// Visible completion and deletion controls, without nested buttons.
assert.match(html,/Marcar como feita: Ir às finanças/);
assert.match(html,/Apagar tarefa: Ir às finanças/);
const onlyDeleted=renderToStaticMarkup(React.createElement(FocusDay,{...props,items:[item('deleted','Tarefa apagada',{deletedAt:'2026-10-07T12:00:00Z'})]}));
assert.doesNotMatch(onlyDeleted,/Tarefa apagada/);
const now='2026-10-07',paused={snoozeUntil:'2026-10-12'};
const cases=[item('today','Hoje',{due:now,...paused}),item('overdue','Vencida',{due:'2026-10-06'}),item('paused','Vencida adiada',{due:'2026-10-06',...paused}),item('review','Revisão',{status:'À espera',reviewOn:now,waitingFor:'Técnico'}),item('approval','Aprovação',{status:'Por aprovar'}),item('resume','Retomar',{snoozeUntil:now}),item('stay','Estadia',{due:'2026-10-09',...paused},'stay'),item('far','Estadia distante',{due:'2026-10-10'},'stay'),item('deleted','Apagada',{due:now,deletedAt:now}),item('closed','Feita',{due:now,status:'Concluído'}),item('contact','Contacto',{due:now},'supplier')];
const warnings=notices(cases,now),has=(id)=>warnings.some(a=>a.id===id);
for(const id of ['today','overdue','review','approval','resume','stay'])assert(has(id),id);
for(const id of ['paused','far','deleted','closed','contact'])assert(!has(id),id);
assert(warnings.find(a=>a.id==='today'&&a.reason==='Prazo hoje'));
assert.equal(warnings.filter(a=>a.id==='stay').length,3);
const undated=item('none','Sem data',{assignee:'Ana'});
assert(assistantItems([undated],now).some(i=>i.id===undated.id));
const organizer=renderToStaticMarkup(React.createElement(Assistant,{items:[undated,...cases],today:now,me:props.me,busy:false,open:()=>{},update:async()=>true,onProposal:()=>{}}));
assert.match(organizer,/Sem data/);assert.match(organizer,/Prazo hoje/);assert.match(organizer,/Fala com o teu Assistente/);
assert.doesNotMatch(organizer,/>Apagada</);
assert.equal(possibleDuplicates([item('dup1','Tarefa Á'),item('dup2','tarefa a')]).length,1);
const notifications=renderToStaticMarkup(React.createElement(Notifications,{items:cases,today:now,name:'Ana',open:()=>{},refresh:()=>{}}));
assert.match(notifications,/6 assuntos precisam de atenção/);
console.log('Task actions, soft-deletion visibility, due dates, snooze exceptions, guest arrivals, review reminders and actionable organizer passed.');

// A newly saved undated task stays visible before the collapsed list, even with older dated work.
const recentItems=[...Array.from({length:4},(_,n)=>item(String(n),'Older dated '+n,{due:'2026-10-07'})),item('new','Saved without deadline')];
const pinned=renderToStaticMarkup(React.createElement(FocusDay,{...props,items:recentItems,highlightedId:'new'}));
assert(pinned.indexOf('Saved without deadline')<pinned.indexOf('Ver os outros'), 'Saved task must be in the visible three rows');
const confirmation=renderToStaticMarkup(React.createElement(RecentTask,{item:recentItems.at(-1),open:()=>{},dismiss:()=>{}}));
assert.match(confirmation,/Tarefa acabada de guardar/);assert.match(confirmation,/Saved without deadline/);
assert.equal(renderToStaticMarkup(React.createElement(RecentTask,{item:item('done','Completed',{status:'Concluído'}),open:()=>{},dismiss:()=>{}})), '');
const employeeDay=renderToStaticMarkup(React.createElement(EmployeeDay,{items:[item('waiting','Wait for technician',{assignee:'Maria',status:'À espera',waitingFor:'Técnico'})],me:{name:'Maria',email:'m@example.test',role:'employee',allowed_areas:['Limpeza da casa']},today:'2026-10-07',busy:false,complete:()=>{},open:()=>{},report:()=>{},history:()=>{}}));
assert.match(employeeDay,/À espera de ajuda/);assert.doesNotMatch(employeeDay,/>Feita</);
assert.doesNotMatch(notifications,/push, com a app fechada, ainda não estão ligadas/);
console.log('PASS: recent undated work remains visible; completed confirmation disappears; waiting work is separated from employee execution.');
