import {createRequire} from 'node:module';
import {mkdirSync} from 'node:fs';
import assert from 'node:assert/strict';
const require=createRequire(import.meta.url),{build}=require(require.resolve('esbuild',{paths:[require.resolve('wrangler')]}));
mkdirSync('.runtime-tests',{recursive:true});
await build({stdin:{contents:"export {default as FocusDay} from './app/focus-day';export {recordSchema} from './lib/model';",resolveDir:process.cwd()},bundle:true,platform:'node',format:'cjs',jsx:'automatic',external:['react','react-dom','react-dom/server'],outfile:'.runtime-tests/dashboard.cjs'});
const {FocusDay,recordSchema}=require('../.runtime-tests/dashboard.cjs');
const React=require('react'),{renderToStaticMarkup}=require('react-dom/server');
const initial=recordSchema.parse({title:'Tarefa base',area:'Casa'});
const item=(id,title,patch={},kind='task')=>({id,kind,data:{...initial,title,...patch},version:1,updated_at:'2026-10-07T14:11:00Z',created_by:'ana@test.pt'});
const props={me:{name:'Ana',role:'admin'},today:'2026-10-07',initial,refresh:async()=>{},open:()=>{},create:()=>{}};
// A saved task with no date or selected daily plan must be visible immediately.
const html=renderToStaticMarkup(React.createElement(FocusDay,{...props,items:[item('1','Ir às finanças',{assignee:'Afonso Marques',area:'Quinta · Arruda'}),item('2','Fechado',{status:'Concluído'}),item('3','Cancelado',{status:'Cancelado'}),item('4','Contacto',{},'supplier'),item('5','Aguardar orçamento',{status:'À espera',waitingFor:'Técnico'}),item('6','Adiado',{snoozeUntil:'2026-10-10'})]}));
assert.match(html,/Assuntos em aberto/);
assert.match(html,/Ir às finanças/);
assert.match(html,/Afonso Marques/);
assert.match(html,/Quinta · Arruda/);
assert.match(html,/Sem prazo/);
assert.match(html,/Aguardar orçamento/);
assert.match(html,/Adiado/);
assert.doesNotMatch(html,/>Fechado</);
assert.doesNotMatch(html,/>Cancelado</);
assert.doesNotMatch(html,/>Contacto</);
assert.doesNotMatch(html,/Outros assuntos/);
assert.match(html,/Filtrar assuntos por responsável/);
assert.match(html,/Filtrar assuntos por espaço/);
const empty=renderToStaticMarkup(React.createElement(FocusDay,{...props,items:[]}));
assert.match(empty,/Ainda não há assuntos em aberto/);
console.log('Dashboard regression passed: undated/unplanned tasks visible; waiting and snoozed tasks retained; closed records and contacts excluded.');
