import {createRequire} from 'node:module';
import {mkdirSync} from 'node:fs';
import assert from 'node:assert/strict';
const require=createRequire(import.meta.url),{build}=require(require.resolve('esbuild',{paths:[require.resolve('wrangler')]}));
mkdirSync('.runtime-tests',{recursive:true});
const runtime=`export const env={SUPABASE_URL:'https://test.supabase.co',SUPABASE_SECRET_KEY:'test-secret',SUPABASE_PUBLISHABLE_KEY:'test-public'};export const jar=new Map();export async function cookies(){return {get:k=>jar.has(k)?{value:jar.get(k)}:undefined,set:(k,v)=>jar.set(k,v),delete:k=>jar.delete(k)}};`;
await build({stdin:{contents:`export * as records from './app/api/records/route';export * as login from './app/api/auth/login/route';export * as verify from './app/api/auth/verify/route';export * as day from './app/api/day/route';export * as team from './app/api/team/route';export {jar} from 'cloudflare:workers';`,resolveDir:process.cwd()},bundle:true,platform:'node',format:'cjs',outfile:'.runtime-tests/app.cjs',plugins:[{name:'runtime',setup(b){b.onResolve({filter:/^(cloudflare:workers|next\/headers)$/},()=>({path:'runtime',namespace:'test'}));b.onLoad({filter:/.*/,namespace:'test'},()=>({contents:runtime,loader:'js'}));}}]});
const app=require('../.runtime-tests/app.cjs');
let identity='ana@test.pt';const tables={members:[{email:identity,name:'Ana',role:'admin'},{email:'cleaner@test.pt',name:'Maria',role:'employee'}],records:[],settings:[{key:'owner',value:identity}],audit:[],files:[]};
const json=(d,status=200)=>Response.json(d,{status});
global.fetch=async(url,opt={})=>{const u=new URL(url);if(u.pathname==='/auth/v1/user')return opt.headers.Authorization==='Bearer valid'?json({email:identity,email_confirmed_at:'2026-10-07'}):json({},401);if(u.pathname==='/auth/v1/otp')return json({});if(u.pathname==='/auth/v1/verify')return JSON.parse(opt.body).token==='123456'?json({access_token:'valid',refresh_token:'refresh',expires_in:3600}):json({},400);if(u.pathname==='/auth/v1/token')return json({access_token:'valid',refresh_token:'refresh'});
assert.equal(opt.headers.apikey,'test-secret');const table=u.pathname.split('/').pop();assert(table in tables);let rows=tables[table];for(const [key,val] of u.searchParams){if(val.startsWith('eq.'))rows=rows.filter(r=>String(r[key])===val.slice(3));}
const method=opt.method||'GET';if(method==='POST'){const data=JSON.parse(opt.body),key=u.searchParams.get('on_conflict');if(key){const old=tables[table].find(r=>r[key]===data[key]);if(old){Object.assign(old,data);return json([old]);}}tables[table].push(data);return json([data]);}if(method==='PATCH'){const data=JSON.parse(opt.body);rows.forEach(r=>Object.assign(r,data));return json(rows);}const offset=Number(u.searchParams.get('offset')||0),limit=Number(u.searchParams.get('limit')||1000);return json(rows.slice(offset,offset+limit));};
const req=(body,path='records',origin='https://app.test')=>new Request('https://app.test/api/'+path,{method:'POST',headers:{origin,'content-type':'application/json'},body:JSON.stringify(body)});
const get=()=>app.records.GET(new Request('https://app.test/api/records'));
assert.equal((await get()).status,401);
assert.equal((await app.login.POST(req({email:'unknown@test.pt'}))).status,403);
assert.equal((await app.verify.POST(req({email:identity,code:'bad'}))).status,400);
assert.equal((await app.verify.POST(req({email:identity,code:'123456'}))).status,200);
assert.equal(app.jar.get('ced-access'),'valid');
assert.equal((await get()).status,200);
assert.equal((await app.records.POST(req({kind:'task',data:{title:'Limpar casa',area:'Casa',assignee:'Maria',due:'2026-10-07',repeat:'Semanal'}}))).status,200);
let item=(await (await get()).json()).items[0];
assert.equal((await app.records.POST(req({...item,version:0}))).status,409);
assert.equal((await app.records.POST(req({...item,data:{...item.data,status:'Concluído'}}))).status,200);
assert(tables.records.some(r=>r.data.due==='2026-10-14'));
assert.equal((await app.records.POST(req({kind:'task',data:{title:'Família',area:'Família'}}))).status,200);
identity='cleaner@test.pt';const visible=(await (await get()).json()).items;assert.equal(visible.length,2);assert(visible.every(i=>i.data.area!=='Família'));
assert.equal((await app.team.POST(req({name:'Intruso',email:'x@test.pt',role:'admin'}))).status,403);
assert.equal((await app.records.POST(req({kind:'purchase',data:{title:'Comprar',area:'Casa'}}))).status,403);
assert.equal((await app.records.POST(req({...visible[0],data:{...visible[0].data,status:'Aprovado'}}))).status,403);
assert.equal((await app.day.POST(req({ids:[visible[0].id],date:'2026-10-07'}))).status,200);
assert.equal((await app.records.POST(req({kind:'task',data:{title:'CSRF',area:'Casa'}},'records','https://other.test'))).status,403);
app.jar.clear();assert.equal((await get()).status,401);
console.log('PASS: email authorization, invalid OTP, verified cookie session, CRUD, concurrent-version conflict, recurrence, employee permissions, private focus and cross-origin rejection. Supabase transport simulated.');
