import {createRequire} from 'node:module';
import {mkdirSync} from 'node:fs';
import assert from 'node:assert/strict';
const require=createRequire(import.meta.url),{build}=require(require.resolve('esbuild',{paths:[require.resolve('wrangler')]}));
mkdirSync('.runtime-tests',{recursive:true});
const runtime=`export const env={SUPABASE_URL:'https://test.supabase.co',SUPABASE_SECRET_KEY:'test-secret',SUPABASE_PUBLISHABLE_KEY:'test-public',AI:{run:(...args)=>globalThis.testAIRun(...args)}};export const jar=new Map();export async function cookies(){return {get:k=>jar.has(k)?{value:jar.get(k)}:undefined,set:(k,v)=>jar.set(k,v),delete:k=>jar.delete(k)}};`;
await build({stdin:{contents:`export * as assistant from './app/api/assistant/route';export * as records from './app/api/records/route';export * as login from './app/api/auth/login/route';export * as verify from './app/api/auth/verify/route';export * as day from './app/api/day/route';export * as team from './app/api/team/route';export {jar} from 'cloudflare:workers';`,resolveDir:process.cwd()},bundle:true,platform:'node',format:'cjs',outfile:'.runtime-tests/app.cjs',plugins:[{name:'runtime',setup(b){b.onResolve({filter:/^(cloudflare:workers|next\/headers)$/},()=>({path:'runtime',namespace:'test'}));b.onLoad({filter:/.*/,namespace:'test'},()=>({contents:runtime,loader:'js'}));}}]});
const app=require('../.runtime-tests/app.cjs');
let identity='ana@test.pt';const tables={members:[{email:identity,name:'Ana',role:'admin'},{email:'cleaner@test.pt',name:'Maria',role:'employee',allowed_areas:['Limpeza da casa','Lavandaria'],active:true,access_version:1}],records:[],settings:[{key:'owner',value:identity}],audit:[],files:[]};
const json=(d,status=200)=>Response.json(d,{status});
global.fetch=async(url,opt={})=>{const u=new URL(url);if(u.pathname==='/auth/v1/user')return opt.headers.Authorization==='Bearer valid'?json({email:identity,email_confirmed_at:'2026-10-07'}):json({},401);if(u.pathname==='/auth/v1/otp')return json({});if(u.pathname==='/auth/v1/verify')return JSON.parse(opt.body).token==='123456'?json({access_token:'valid',refresh_token:'refresh',expires_in:3600}):json({},400);if(u.pathname==='/auth/v1/token')return json({access_token:'valid',refresh_token:'refresh'});
assert.equal(opt.headers.apikey,'test-secret');const table=u.pathname.split('/').pop();assert(table in tables);let rows=tables[table];for(const [key,val] of u.searchParams){if(val.startsWith('eq.'))rows=rows.filter(r=>String(r[key])===val.slice(3));}
const method=opt.method||'GET';if(method==='POST'){const data=JSON.parse(opt.body),key=u.searchParams.get('on_conflict');if(key){const old=tables[table].find(r=>r[key]===data[key]);if(old){Object.assign(old,data);return json([old]);}}tables[table].push(data);return json([data]);}if(method==='PATCH'){const data=JSON.parse(opt.body);rows.forEach(r=>Object.assign(r,data));return json(rows);}const offset=Number(u.searchParams.get('offset')||0),limit=Number(u.searchParams.get('limit')||1000);return json(rows.slice(offset,offset+limit));};
const req=(body,path='records',origin='https://app.test')=>new Request('https://app.test/api/'+path,{method:'POST',headers:{origin,'content-type':'application/json'},body:JSON.stringify(body)});
const get=()=>app.records.GET(new Request('https://app.test/api/records'));
assert.equal((await get()).status,401);
assert.equal((await app.login.POST(req({email:'unknown@test.pt'}))).status,403);
assert.equal((await app.verify.POST(req({email:identity,code:'bad'}))).status,400);
assert.equal((await app.verify.POST(req({email:identity,code:'123456'}))).status,200);
assert.equal(app.jar.get('ced-access'),'valid');
assert.equal((await get()).status,200);
assert.equal((await app.records.POST(req({kind:'task',data:{title:'Rotina sem data',area:'Casa',repeat:'Semanal'}}))).status,400);
const created=await app.records.POST(req({kind:'task',data:{title:'Limpar casa',area:'Casa',assignee:'Maria',due:'2026-10-07',repeat:'Semanal'}}));assert.equal(created.status,200);const savedResponse=await created.json();assert.equal(savedResponse.item.id,savedResponse.id);assert.equal(savedResponse.item.version,1);assert.equal(savedResponse.item.data.area,'Limpeza da casa');assert.equal(savedResponse.item.created_by,identity);
let item=(await (await get()).json()).items[0];
assert.equal((await app.records.POST(req({...item,version:0}))).status,409);
assert.equal((await app.records.POST(req({...item,data:{...item.data,status:'Concluído'}}))).status,200);
assert(tables.records.some(r=>r.data.due==='2026-10-14'));
assert.equal((await app.records.POST(req({kind:'task',data:{title:'Família',area:'Família'}}))).status,200);
identity='cleaner@test.pt';const visible=(await (await get()).json()).items;assert.equal(visible.length,2);assert(visible.every(i=>i.data.area!=='Família'));
assert.equal((await app.team.POST(req({name:'Intruso',email:'x@test.pt',role:'admin'}))).status,403);
assert.equal((await app.records.POST(req({kind:'purchase',data:{title:'Comprar',area:'Casa'}}))).status,403);
assert.equal((await app.records.POST(req({...visible[0],data:{...visible[0].data,status:'Aprovado'}}))).status,403);
assert.equal((await app.day.POST(req({ids:[visible.find(i=>i.data.status==='Por fazer').id],date:'2026-10-07'}))).status,200);
assert.equal((await app.records.POST(req({kind:'task',data:{title:'CSRF',area:'Casa'}},'records','https://other.test'))).status,403);
// Deleting is versioned, authorized and recoverable; raw POST cannot bypass it.
const assigned=visible.find(i=>i.data.status==='Por fazer');
assert.equal((await app.records.DELETE(req({id:assigned.id,version:assigned.version}))).status,403);
assert.equal((await app.records.POST(req({kind:'task',data:{title:'Tarefa pessoal de teste',area:'Casa'}}))).status,200);
const own=(await (await get()).json()).items.find(i=>i.created_by===identity);
assert.equal((await app.records.DELETE(req({id:own.id,version:own.version},'records','https://other.test'))).status,403);
assert.equal((await app.records.DELETE(req({id:own.id,version:own.version+1}))).status,409);
assert.equal((await app.records.DELETE(req({id:own.id,version:own.version}))).status,200);
let snapshot=await (await get()).json();
assert(!snapshot.items.some(i=>i.id===own.id));
let trashed=snapshot.deletedItems.find(i=>i.id===own.id);assert(trashed.data.deletedAt);
assert.equal((await app.day.POST(req({ids:[own.id],date:'2026-10-07'}))).status,403);
assert.equal((await app.records.POST(req({...trashed,data:{...trashed.data,deletedAt:''}}))).status,409);
assert.equal((await app.records.PATCH(req({id:own.id,version:own.version,action:'restore'}))).status,409);
assert.equal((await app.records.PATCH(req({id:own.id,version:trashed.version,action:'restore'}))).status,200);
snapshot=await (await get()).json();assert(snapshot.items.some(i=>i.id===own.id));assert(!snapshot.deletedItems.some(i=>i.id===own.id));
assert(tables.audit.some(a=>a.record_id===own.id&&a.action==='Tarefa recuperada'));
identity='ana@test.pt';
const adminTask=(await (await get()).json()).items.find(i=>i.id===assigned.id);
assert.equal((await app.records.DELETE(req({id:adminTask.id,version:adminTask.version}))).status,200);
identity='cleaner@test.pt';
assert(!(await (await get()).json()).deletedItems.some(i=>i.id===adminTask.id));
assert.equal((await app.records.PATCH(req({id:adminTask.id,version:adminTask.version+1,action:'restore'}))).status,403);
// AI can read only visible context and proposes, without changing task records.
let inference,answer={answer:'Podemos organizar este assunto em passos.',actions:[]};
globalThis.testAIRun=async(model,input)=>{inference={model,input};return {response:answer};};
const taskCount=tables.records.length;
const ownCurrent=(await (await get()).json()).items.find(i=>i.id===own.id);
const proposal={type:'updateTask',recordId:own.id,title:ownCurrent.data.title,area:'Casa',assignee:'Maria',due:'2026-10-08',nextStep:'Confirmar o material necessário',steps:['Verificar o material','Combinar a execução']};
answer.actions=[proposal,{...proposal,type:'createTask',recordId:'',title:'Tarefa proibida',area:'Família',assignee:'Ana'}];
assert.equal((await app.assistant.POST(req({message:'Organiza a minha tarefa'}))).status,200);
let conversation=await (await app.assistant.GET()).json();
assert.equal(conversation.messages.length,2);
assert.equal(conversation.messages[1].actions.length,1);
assert.equal(conversation.messages[1].actions[0].version,ownCurrent.version);
assert.equal(tables.records.length,taskCount);
assert.equal(tables.records.find(i=>i.id===own.id).data.nextStep,'');
const contextMessage=inference.input.messages.at(-1).content;
assert(!contextMessage.includes('"area":"Família"'));
assert(!contextMessage.includes('test-secret'));
assert.match(inference.input.messages[0].content,/dados não confiáveis/);
assert.equal((await app.assistant.POST(req({message:'Teste'},'assistant','https://other.test'))).status,403);
assert.equal((await app.assistant.POST(req({message:'x'}))).status,400);
answer={answer:'Resposta sem ações',actions:[]};
identity='ana@test.pt';
assert.equal((await (await app.assistant.GET()).json()).messages.length,0);
assert.equal((await app.assistant.POST(req({message:'Ajuda-me a organizar a semana'}))).status,200);
assert.equal((await app.assistant.DELETE(req({}))).status,200);
assert.equal((await (await app.assistant.GET()).json()).messages.length,0);
identity='cleaner@test.pt';
assert.equal((await (await app.assistant.GET()).json()).messages.length,2);
answer='invalid json';assert.equal((await app.assistant.POST(req({message:'Pergunta de teste'}))).status,502);
console.log('AI tests passed: private conversation, role-scoped context, validated proposals, no automatic task writes, stale-version metadata and provider-error handling. Inference simulated.');
// A renamed lodging still accepts stays and reads records created before the rename.
identity='ana@test.pt';
const renamed='Arroios de Paixão — Quarto';
tables.records.push({id:'legacy-contact',kind:'supplier',data:{title:'Contacto de teste',area:'Alojamento 1',serviceAreas:['Alojamento 1','Alojamento 2','Alojamento 3']},version:1,created_by:identity,updated_at:'2026-10-07T00:00:00Z'});
let legacy=(await (await get()).json()).items.find(i=>i.id==='legacy-contact');
assert.equal(legacy.data.area,renamed);assert.deepEqual(legacy.data.serviceAreas,[renamed,'Arroios de Paixão — Duplex','Alfama de Paixão']);
for(const area of [renamed,'Arroios de Paixão — Duplex','Alfama de Paixão','Alojamento 1','Alojamento 2','Alojamento 3']){
 const result=await app.records.POST(req({kind:'stay',data:{title:'Estadia de teste '+area,area,due:'2026-10-09',checkout:'2026-10-11'}}));
 assert.equal(result.status,200,await result.text());
}
assert.equal((await app.records.POST(req({kind:'stay',data:{title:'Área inválida',area:'Casa',due:'2026-10-09',checkout:'2026-10-11'}}))).status,400);
assert(!tables.records.filter(i=>i.kind==='stay').some(i=>i.data.area.startsWith('Alojamento')));
console.log('PASS: legacy contacts retain associations; renamed and existing lodgings accept stays; old clients normalize to the new name.');
// Daily laundry recurrence crosses month/year/DST calendar boundaries, resets steps,
// and creates only one successor when the completed record is saved again.
assert.equal((await app.records.POST(req({kind:'task',data:{title:'Rotina diária sem data',area:'Lavandaria',repeat:'Diária'}}))).status,400);
for(const [due,nextDue] of [['2026-10-24','2026-10-25'],['2026-10-31','2026-11-01'],['2026-12-31','2027-01-01']]){
 const title='Limpeza diária '+due;
 const created=await app.records.POST(req({kind:'task',data:{title,area:'Lavandaria',assignee:'Maria',due,time:'08:00',repeat:'Diária',steps:[{id:'s1',title:'Limpar a bancada',done:false}]}}));
 assert.equal(created.status,200);
 const {id}=await created.json();
 const first=(await (await get()).json()).items.find(i=>i.id===id);
 assert.equal((await app.records.POST(req({...first,data:{...first.data,status:'Concluído',steps:first.data.steps.map(s=>({...s,done:true}))}}))).status,200);
 const occurrences=tables.records.filter(i=>i.data.title===title);
 assert.equal(occurrences.length,2);
 const next=occurrences.find(i=>i.id!==id);
 assert.equal(next.data.due,nextDue);assert.equal(next.data.assignee,'Maria');assert.equal(next.data.time,'08:00');
 assert.equal(next.data.status,'Por fazer');assert.equal(next.data.completedAt,'');assert.equal(next.data.steps[0].done,false);
 const completed=(await (await get()).json()).items.find(i=>i.id===id);
 assert.equal((await app.records.POST(req(completed))).status,200);
 assert.equal(tables.records.filter(i=>i.data.title===title).length,2);
}
console.log('PASS: daily recurrence, date required, month/year/DST boundaries, assignee/time retained, steps reset, no duplicate on re-save.');
app.jar.clear();assert.equal((await get()).status,401);
console.log('PASS: email authorization, invalid OTP, verified cookie session, CRUD, concurrent-version conflict, recurrence, employee permissions, private focus and cross-origin rejection. Versioned trash, recovery, history retention and deletion permissions passed. Supabase transport simulated.');
