import {createRequire} from 'node:module';
import assert from 'node:assert/strict';
import {readdirSync,readFileSync} from 'node:fs';
import {resolve} from 'node:path';
import {createECDH,randomBytes} from 'node:crypto';
let subscriptionRow,providerCalls=0;
const base=resolve('dist/server');const paths=['index.js',...readdirSync(base,{recursive:true}).filter(p=>p.endsWith('.js')&&p!=='index.js')];
const require=createRequire(process.cwd()+'/package.json');
const {Miniflare}=require(require.resolve('miniflare',{paths:[require.resolve('wrangler')]}));
const configRows=[];
const mf=new Miniflare({modules:paths.map(p=>({type:'ESModule',path:resolve(base,p),contents:readFileSync(resolve(base,p),'utf8')})),modulesRoot:base,compatibilityDate:'2026-05-01',compatibilityFlags:['nodejs_compat'],bindings:{SUPABASE_URL:'https://test.supabase.co',SUPABASE_PUBLISHABLE_KEY:'public',SUPABASE_SECRET_KEY:'test-secret'},outboundService:async req=>{const u=new URL(req.url);if(u.pathname==='/auth/v1/user')return Response.json({email:'test@example.test',email_confirmed_at:'2026-10-01'});if(u.pathname==='/rest/v1/members')return Response.json([{name:'Test',email:'test@example.test',role:'admin'}]);if(u.pathname==='/rest/v1/push_config')return Response.json(configRows);if(u.pathname==='/rest/v1/rpc/ced_push_config'){const p=await req.json();configRows.push({id:true,public_key:p.p_public,private_key:p.p_private});return Response.json(configRows[0]);}if(u.pathname==='/rest/v1/push_subscriptions'){if(req.method==='POST'){subscriptionRow=await req.json();return Response.json([subscriptionRow]);}return Response.json(subscriptionRow?[subscriptionRow]:[]);}if(u.pathname==='/rest/v1/rpc/ced_claim_push')return Response.json(true);if(u.pathname==='/rest/v1/push_deliveries')return Response.json([]);if(u.hostname==='web.push.apple.com'){providerCalls++;assert(req.headers.get('authorization').startsWith('vapid '));assert((await req.arrayBuffer()).byteLength>100);return new Response('',{status:201});}throw Error('Unexpected path '+u.pathname);}});
try{const r=await mf.dispatchFetch('http://test/api/push',{headers:{cookie:'ced-access=test'}});const data=await r.json();assert.equal(r.status,200,JSON.stringify(data));assert(data.publicKey);assert.equal(data.publicKey.length,87);assert(!('privateKey' in data));const ecdh=createECDH('prime256v1');ecdh.generateKeys();const subscribe=await mf.dispatchFetch('http://test/api/push',{method:'POST',headers:{cookie:'ced-access=test',origin:'http://test','content-type':'application/json'},body:JSON.stringify({subscription:{endpoint:'https://web.push.apple.com/mocked-test',keys:{p256dh:ecdh.getPublicKey().toString('base64url'),auth:randomBytes(16).toString('base64url')}}})});assert.equal(subscribe.status,200);const {id}=await subscribe.json();const sent=await mf.dispatchFetch('http://test/api/push',{method:'POST',headers:{cookie:'ced-access=test',origin:'http://test','content-type':'application/json'},body:JSON.stringify({action:'test',id})});assert.equal(sent.status,200,await sent.text());assert.equal(providerCalls,1);console.log('PASS: built production Worker authenticated config → subscription → encrypted signed notification in workerd. Database and delivery provider simulated.');}finally{await mf.dispose();}
