'use client';
import {useState} from 'react';
import {cleaningTemplates,linkedCleaning} from '@/lib/cleaning';
import {Item} from '@/lib/model';
export default function CleaningPlanner({stay,items,team,onSaved}:{stay:Item;items:Item[];team:{name:string;email:string}[];onSaved:()=>Promise<void>}){
 const [assignee,setAssignee]=useState(''),[due,setDue]=useState(stay.data.due),[time,setTime]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const linked=linkedCleaning(items,stay.id),templates=cleaningTemplates(stay.data.area),missing=templates.filter(t=>!linked.some(i=>i.data.cleaningTemplateId===t.id));
 const create=async()=>{if(!assignee||!due){setError('Escolhe responsável e data.');return;}setBusy(true);setError('');try{const r=await fetch('/api/cleaning',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({stayId:stay.id,version:stay.version,assignee,due,time})});if(!r.ok){let message=await r.text();try{message=JSON.parse(message).error||message;}catch{}throw new Error(message);}await onSaved();}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 return <section className="subsection cleaning-plan"><h3>Limpeza ligada à estadia</h3><p>{linked.length?`${linked.filter(i=>i.data.status==='Concluído').length} de ${linked.length} tarefas concluídas. O estado acompanha as tarefas.`:'Cria as listas deste alojamento com um responsável e uma data até à entrada.'}</p>{linked.map(i=><div className="cleaning-task" key={i.id}><strong>{i.data.title}</strong><small>{i.data.assignee} · {i.data.due} · {i.data.status}</small></div>)}{missing.length>0&&!['Concluído','Cancelado'].includes(stay.data.status)&&<><p>Por preparar: {missing.map(t=>t.label).join('; ')}.</p><div className="form-grid"><label className="field"><span>Quem limpa?</span><select value={assignee} onChange={e=>setAssignee(e.target.value)} disabled={busy}><option value="">Escolher uma pessoa</option>{team.map(m=><option key={m.email}>{m.name}</option>)}</select></label><label className="field"><span>Dia da limpeza</span><input type="date" max={stay.data.due} value={due} onChange={e=>setDue(e.target.value)} disabled={busy}/></label><label className="field"><span>Hora limite, se combinada</span><input type="time" value={time} onChange={e=>setTime(e.target.value)} disabled={busy}/></label></div><button type="button" className="secondary" disabled={busy} onClick={create}>{busy?'A criar…':`Criar ${missing.length} tarefas de limpeza`}</button><small>Usa a estadia guardada. Se alteraste as datas acima, guarda primeiro. As listas não incluem contactos dos hóspedes.</small></>}{error&&<p className="errorbox" role="alert">{error}</p>}</section>;
}
