'use client';
import {useState} from 'react';
import {Check,Camera,ChevronRight,Clock} from 'lucide-react';
import {Item,isOpen,memberAreas,Member} from '@/lib/model';
export default function EmployeeDay({items,me,today,busy,complete,open,report,history}:{items:Item[];me:Member;today:string;busy:boolean;complete:(i:Item)=>void;open:(i:Item)=>void;report:(area:string,item?:Item)=>void;history:()=>void}){
 const [selected,setSelected]=useState('Todos');const allowed=memberAreas(me);
 const tasks=items.filter(i=>i.kind==='task'&&isOpen(i)&&(selected==='Todos'||i.data.area===selected));
 const current=tasks.filter(i=>(!i.data.due||i.data.due<=today)&&(!i.data.snoozeUntil||i.data.snoozeUntil<=today||i.data.due===today));
 const later=tasks.filter(i=>!current.includes(i)).sort((a,b)=>(a.data.due||'9999').localeCompare(b.data.due||'9999'));
 const finished=items.filter(i=>i.kind==='task'&&i.data.status==='Concluído'&&i.data.completedAt&&new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Lisbon',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(i.data.completedAt))===today).length;
 const card=(i:Item)=><article className="simple-task" key={i.id}><div className="simple-task-meta"><span>{i.data.time|| (i.data.due&&i.data.due<today?'Por terminar':i.data.due>today?new Date(i.data.due+'T12:00:00Z').toLocaleDateString('pt-PT',{day:'numeric',month:'short'}):'Hoje')}</span>{i.data.priority!=='Normal'&&<span className="badge urgent">{i.data.priority}</span>}{i.data.status==='À espera'&&<span className="badge waiting">À espera</span>}</div><h3>{i.data.title}</h3>{i.data.status==='À espera'&&i.data.waitingFor&&<p>À espera de {i.data.waitingFor}</p>}<div className="simple-task-buttons"><button className="done-button" disabled={busy} onClick={()=>complete(i)}><Check size={22}/>Feita</button><button className="secondary" disabled={busy} onClick={()=>report(i.data.area,i)}><Camera size={20}/>Há um problema</button></div><details className="task-instructions"><summary>Ver instruções {i.data.steps.length?`· ${i.data.steps.length} passos`:''}</summary>{i.data.description&&<p className="preserve-lines">{i.data.description}</p>}{i.data.steps.length>0&&<ol>{i.data.steps.map(s=><li key={s.id}>{s.done?'✓ ':''}{s.title}</li>)}</ol>}<button className="textbutton" onClick={()=>open(i)}>Passos, fotografias e histórico<ChevronRight size={16}/></button></details></article>;
 return <div className="employee-day"><div className="employee-summary"><strong>{current.length?`${current.length} ${current.length===1?'tarefa por fazer':'tarefas por fazer'}`:'Tudo tratado por agora'}</strong><button className="textbutton" onClick={history}>{finished} feitas hoje</button></div>{allowed.length>1&&<div className="scope-chips" aria-label="Filtrar espaço">{['Todos',...allowed].map(a=><button key={a} aria-pressed={selected===a} onClick={()=>setSelected(a)}>{a}</button>)}</div>}{allowed.filter(a=>current.some(i=>i.data.area===a)).map(a=><section className="employee-space" key={a}><h2>{a}</h2>{current.filter(i=>i.data.area===a).sort((x,y)=>(x.data.time||'99').localeCompare(y.data.time||'99')).map(card)}</section>)}{!current.length&&<div className="simple-empty"><Check size={30}/><p>{allowed.length?'Quando houver trabalho para ti, aparece aqui.':'A responsável ainda precisa de escolher os teus espaços.'}</p></div>}{later.length>0&&<details className="panel future-tasks"><summary><Clock size={18}/>Próximas tarefas · {later.length}</summary>{later.map(i=><div key={i.id}><p className="muted">{i.data.area}</p>{card(i)}</div>)}</details>}<button className="secondary report-bottom" disabled={!allowed.length} onClick={()=>report(selected==='Todos'?allowed[0]:selected)}><Camera size={20}/>Reportar algo ou pedir material</button></div>;
}
