'use client';
import {useEffect,useState} from 'react';
import {Plus,Camera,Check,ArrowRight} from 'lucide-react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Checkbox} from '@/components/ui/checkbox';
import {toast} from 'sonner';
import {areas,Data,Item,notices} from '@/lib/model';
const closed=(i:Item)=>['Concluído','Cancelado'].includes(i.data.status);
const format=(s:string)=>s?new Date(s+'T12:00:00').toLocaleDateString('pt-PT',{day:'numeric',month:'short'}):'Sem data';
async function checked(r:Response):Promise<any>{if(!r.ok){const t=await r.text();let message=t;try{message=JSON.parse(t).error||t;}catch{}throw new Error(message);}return r.json();}
export default function FocusDay({items,me,today,initial,refresh,open,create}:{items:Item[];me:{name:string;role:string};today:string;initial:Data;refresh:()=>Promise<void>;open:(i:Item)=>void;create:(kind:Item['kind'])=>void}){
 const [plan,setPlan]=useState<{date:string;ids:string[]}>({date:'',ids:[]});
 const [ready,setReady]=useState(false),[planError,setPlanError]=useState(''),[busy,setBusy]=useState(false);
 const [choosing,setChoosing]=useState(false),[selection,setSelection]=useState<string[]>([]),[search,setSearch]=useState('');
 const [listArea,setListArea]=useState('Todos os espaços'),[listPerson,setListPerson]=useState('Toda a equipa');
 const [title,setTitle]=useState(''),[space,setSpace]=useState('Casa'),[kind,setKind]=useState('task');
 const [action,setAction]=useState<{item:Item;type:'wait'|'snooze'}|null>(null),[when,setWhen]=useState(''),[who,setWho]=useState('');
 const admin=me.role==='admin';
 const fetchPlan=async()=>{try{setPlan(await checked(await fetch('/api/day')));setReady(true);setPlanError('');}catch(e){setPlanError((e as Error).message);}};
 useEffect(()=>{fetchPlan();},[]);
 const ids=plan.date===today?plan.ids:[];
 const active=items.filter(i=>i.kind!=='supplier'&&!closed(i));
 const eligible=active.filter(i=>i.data.status!=='À espera'&&(!i.data.snoozeUntil||i.data.snoozeUntil<=today||(i.data.due&&i.data.due<=today)));
 const chosen=ids.map(id=>eligible.find(i=>i.id===id)).filter(Boolean) as Item[];
 const current=chosen[0];
 const waiting=active.filter(i=>i.data.status==='À espera');
 const pending=notices(items,today);
 const urgentIds=new Set(pending.map(a=>a.id));
 const needs=active.filter(i=>urgentIds.has(i.id));
 const visible=active.filter(i=>(listArea==='Todos os espaços'||i.data.area===listArea)&&(listPerson==='Toda a equipa'||i.data.assignee===listPerson)).sort((a,b)=>(a.data.due||'9999').localeCompare(b.data.due||'9999')||b.updated_at.localeCompare(a.updated_at));
 const focusNow=async(i:Item)=>{if(busy)return;setBusy(true);try{await savePlan([i.id,...chosen.filter(x=>x.id!==i.id).map(x=>x.id)].slice(0,3));toast.success('Está em foco para hoje.');}catch(e){toast.error((e as Error).message);}finally{setBusy(false);}};
 const savePlan=async(next:string[])=>{const value=await checked(await fetch('/api/day',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({date:today,ids:next})}));setPlan(value);};
 const update=async(i:Item,patch:Partial<Data>)=>{if(busy)return;setBusy(true);try{await checked(await fetch('/api/records',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:i.id,kind:i.kind,version:i.version,data:{...i.data,...patch}})}));await refresh();toast.success(patch.status==='Concluído'?'Feito. Menos uma coisa para pensar.':'Guardado.');setAction(null);}catch(e){toast.error((e as Error).message);await refresh();}finally{setBusy(false);}};
 const capture=async(e:React.FormEvent)=>{e.preventDefault();if(busy)return;setBusy(true);try{await checked(await fetch('/api/records',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({kind,data:{...initial,title:title.trim(),area:space,assignee:me.name}})}));setTitle('');await refresh();toast.success('Guardado. Já aparece nos assuntos em aberto.');}catch(e){toast.error((e as Error).message);}finally{setBusy(false);}};
 const startAction=(i:Item,type:'wait'|'snooze')=>{setAction({item:i,type});setWhen(type==='wait'?i.data.reviewOn:i.data.snoozeUntil);setWho(i.data.waitingFor);};
 const choose=()=>{setSelection(ids.filter(id=>eligible.some(i=>i.id===id)));setSearch('');setChoosing(true);};
 const simpleRow=(i:Item)=><button key={i.id} className="record-row" onClick={()=>open(i)}><span className="row-main"><strong>{i.data.title}</strong><span>{i.data.area} · {i.data.assignee}</span>{i.data.status==='À espera'&&<span>À espera de {i.data.waitingFor||'responsável por indicar'} · verificar {format(i.data.reviewOn)}</span>}{i.data.snoozeUntil>today&&<span>Volta ao foco em {format(i.data.snoozeUntil)}</span>}</span><span className="row-end"><span className="badge">{i.data.status}</span><small>{i.data.due?'Prazo: '+format(i.data.due):'Sem prazo'}</small></span><ArrowRight size={17}/></button>;
 return <div className="focus-day">
 <section className={"focus-card "+(!current?"focus-card-idle":"")} aria-label="Tarefa em foco"><div className="section-top"><h2>Agora</h2><button className="textbutton" disabled={!ready||busy} onClick={choose}>{chosen.length?'Escolher outra':'Escolher prioridades'}</button></div>
 {planError&&<p role="alert" className="errorbox">Não foi possível carregar as prioridades. <button onClick={fetchPlan}>Tentar novamente</button></p>}
 {!ready&&!planError?<p className="quiet-empty">A recuperar o teu dia…</p>:current?<><p className="eyebrow">{current.data.area} · {current.data.status==='Em curso'?'Ficaste aqui':current.data.assignee}</p><h3>{current.data.title}</h3><p className="focus-next">{current.data.steps.find(s=>!s.done)?.title||current.data.nextStep||'Define um pequeno primeiro passo nos detalhes.'}</p>{current.data.due&&<p className="focus-date">Prazo: {format(current.data.due)} {current.data.time}</p>}
 {current.data.steps.length>0&&<div className="focus-steps">{current.data.steps.map(step=><label key={step.id}><Checkbox checked={step.done} disabled={busy} onCheckedChange={v=>update(current,{steps:current.data.steps.map(s=>s.id===step.id?{...s,done:v===true}:s)})}/><span className={step.done?'step-done':''}>{step.title}</span></label>)}</div>}
 <div className="focus-actions">{current.data.status!=='Em curso'&&<button className="primary" disabled={busy} onClick={()=>update(current,{status:'Em curso',snoozeUntil:''})}>Começar</button>}<button className={current.data.status==='Em curso'?'primary':'secondary'} disabled={busy} onClick={()=>update(current,{status:'Concluído',steps:current.data.steps.map(s=>({...s,done:true}))})}><Check size={17}/>Concluído</button><button className="secondary" disabled={busy} onClick={()=>startAction(current,'wait')}>Preciso de ajuda</button><button className="textbutton" disabled={busy} onClick={()=>startAction(current,'snooze')}>Adiar até…</button><button className="textbutton" onClick={()=>open(current)}>Detalhes</button></div></>:ready?<div className="focus-empty"><h3>As tuas prioridades</h3><p>Se quiseres, escolhe até três assuntos para te concentrares hoje.</p>{ids.length>0&&<p>Os assuntos concluídos, adiados ou à espera já saíram do foco.</p>}<button className="primary" disabled={busy} onClick={choose}>Escolher o que fazer</button></div>:null}
 </section>
 {chosen.length>1&&<section className="day-section"><div className="section-top"><h2>Depois</h2><span className="muted">Ao teu ritmo</span></div><div className="panel">{chosen.slice(1).map(i=><div className="next-choice" key={i.id}>{simpleRow(i)}<button disabled={busy} className="textbutton" onClick={async()=>{setBusy(true);try{await savePlan([i.id,...ids.filter(id=>id!==i.id)]);}catch(e){toast.error((e as Error).message);}finally{setBusy(false);}}}>Fazer agora</button></div>)}</div></section>}
 <section className="day-section" aria-label="Assuntos em aberto"><div className="section-top"><h2>Assuntos em aberto <span className="count">{active.length}</span></h2><button className="textbutton" onClick={()=>create('task')}><Plus size={17}/>Tarefa</button></div><div className="panel"><div className="dashboard-filters"><Select value={listArea} onValueChange={setListArea}><SelectTrigger aria-label="Filtrar assuntos por espaço"><SelectValue/></SelectTrigger><SelectContent>{['Todos os espaços',...Array.from(new Set(active.map(i=>i.data.area)))].map(a=><SelectItem key={a} value={a}>{a}</SelectItem>)}</SelectContent></Select><Select value={listPerson} onValueChange={setListPerson}><SelectTrigger aria-label="Filtrar assuntos por responsável"><SelectValue/></SelectTrigger><SelectContent>{['Toda a equipa',...Array.from(new Set(active.map(i=>i.data.assignee)))].map(a=><SelectItem key={a} value={a}>{a}</SelectItem>)}</SelectContent></Select></div>{visible.length?visible.map(i=><div className="next-choice" key={i.id}>{simpleRow(i)}{eligible.includes(i)&&!chosen.includes(i)&&<button className="textbutton" disabled={!ready||busy} onClick={()=>focusNow(i)}>Fazer agora</button>}</div>):<p className="quiet-empty">{active.length?'Não há assuntos com estes filtros.':'Ainda não há assuntos em aberto. Adiciona a primeira tarefa.'}</p>}</div></section>
 <section className="capture-card panel"><h2>Tira da cabeça</h2><form onSubmit={capture}><label className="field"><span>O que não queres esquecer?</span><input required minLength={2} maxLength={160} value={title} onChange={e=>setTitle(e.target.value)} placeholder="Ex.: pedir orçamento para o secador"/></label><div className="capture-options"><Select value={space} onValueChange={setSpace}><SelectTrigger aria-label="Espaço"><SelectValue/></SelectTrigger><SelectContent>{areas.filter(a=>admin||a!=='Família').map(a=><SelectItem key={a} value={a}>{a}</SelectItem>)}</SelectContent></Select><Select value={kind} onValueChange={setKind}><SelectTrigger aria-label="Tipo de assunto"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="task">Tarefa</SelectItem><SelectItem value="incident">Algo para arranjar</SelectItem>{admin&&<SelectItem value="purchase">Compra</SelectItem>}</SelectContent></Select><button className="primary" disabled={busy}><Plus size={17}/>Guardar</button></div><button className="textbutton" type="button" onClick={()=>create('incident')}><Camera size={17}/>Reportar com fotografia</button></form></section>
 <section className="day-section"><div className="section-top"><h2>À espera de alguém</h2></div><div className="panel">{waiting.length?waiting.map(simpleRow):<p className="quiet-empty">Não há assuntos à espera.</p>}</div></section>
 <details className="focus-disclosure" open><summary>Precisa de atenção · {needs.length}</summary><div className="panel">{needs.length?needs.map(i=><div key={i.id}>{simpleRow(i)}<p className="reason-line">{pending.filter(a=>a.id===i.id).map(a=>a.reason).join(' · ')}</p></div>):<p className="quiet-empty">Sem pendências sinalizadas.</p>}</div></details>

 <Dialog open={choosing} onOpenChange={v=>!busy&&setChoosing(v)}><DialogContent className="record-dialog"><DialogHeader><DialogTitle>O que importa hoje?</DialogTitle><DialogDescription>Escolhe até três. A ordem de seleção define por onde começar.</DialogDescription></DialogHeader><input aria-label="Procurar assunto" placeholder="Procurar…" value={search} onChange={e=>setSearch(e.target.value)}/><div className="priority-picker">{eligible.filter(i=>(i.data.title+' '+i.data.area).toLowerCase().includes(search.toLowerCase())).map(i=><label key={i.id}><Checkbox checked={selection.includes(i.id)} disabled={busy||(!selection.includes(i.id)&&selection.length===3)} onCheckedChange={v=>setSelection(v?[...selection,i.id]:selection.filter(id=>id!==i.id))}/><span><strong>{i.data.title}</strong><small>{i.data.area} · {format(i.data.due)}{selection.includes(i.id)?' · '+(selection.indexOf(i.id)+1)+'º':''}</small></span></label>)}{!eligible.length&&<p>Adiciona um assunto na captura rápida para começar.</p>}</div><button className="primary" disabled={busy} onClick={async()=>{setBusy(true);try{await savePlan(selection);setChoosing(false);}catch(e){toast.error((e as Error).message);}finally{setBusy(false);}}}>{busy?'A guardar…':'Guardar prioridades'}</button></DialogContent></Dialog>
 <Dialog open={!!action} onOpenChange={v=>!v&&!busy&&setAction(null)}><DialogContent className="record-dialog"><DialogHeader><DialogTitle>{action?.type==='wait'?'À espera de ajuda':'Voltar a este assunto'}</DialogTitle><DialogDescription>{action?.item.data.title} · O prazo original mantém-se. O aviso aparece na app.</DialogDescription></DialogHeader><form onSubmit={e=>{e.preventDefault();if(action)update(action.item,action.type==='wait'?{status:'À espera',waitingFor:who,reviewOn:when,snoozeUntil:''}:{snoozeUntil:when});}}>{action?.type==='wait'&&<label className="field"><span>Quem pode tratar disto?</span><input required maxLength={150} value={who} onChange={e=>setWho(e.target.value)} placeholder="Ex.: marido, empregada ou técnico"/></label>}<label className="field"><span>{action?.type==='wait'?'Voltar a verificar em':'Voltar ao foco em'}</span><input required type="date" min={action?.type==='snooze'?new Date(new Date(today+'T12:00:00Z').getTime()+86400000).toISOString().slice(0,10):today} value={when} onChange={e=>setWhen(e.target.value)}/></label><button className="primary" disabled={busy}>{busy?'A guardar…':'Guardar'}</button></form></DialogContent></Dialog>
 </div>;
}
