'use client';
import {useState} from 'react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Item,Member,memberAreas,recordSchema} from '@/lib/model';
export default function QuickReport({area,item,me,today,onClose,onSaved}:{area:string;item?:Item;me:Member;today:string;onClose:()=>void;onSaved:()=>Promise<void>}){
 const [place,setPlace]=useState(area),[title,setTitle]=useState(''),[note,setNote]=useState(''),[photo,setPhoto]=useState<File|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[savedId,setSavedId]=useState('');
 async function submit(e:React.FormEvent){e.preventDefault();if(busy)return;setBusy(true);setError('');try{let id=savedId;if(!id){const data=recordSchema.parse({title,area:place,description:[note,item?'Detetado durante: '+item.data.title:''].filter(Boolean).join('\n'),assignee:me.name,due:today,status:'À espera',waitingFor:'Gestão',reviewOn:today});const r=await fetch('/api/records',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({kind:'incident',data})});if(!r.ok)throw new Error('Não foi possível guardar. Tenta novamente.');id=((await r.json()) as {id:string}).id;setSavedId(id);}if(photo){const f=new FormData();f.append('recordId',id);f.append('file',photo);const r=await fetch('/api/files',{method:'POST',body:f});if(!r.ok)throw new Error('O problema ficou registado, mas a fotografia não foi enviada. Tenta enviar novamente.');}await onSaved();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <Dialog open onOpenChange={v=>!v&&!busy&&onClose()}><DialogContent className="record-dialog"><DialogHeader><DialogTitle>O que se passa?</DialogTitle><DialogDescription>{item?item.data.title:'Uma frase e, se ajudar, uma fotografia.'}</DialogDescription></DialogHeader><form onSubmit={submit} className="record-form"><label className="field"><span>Espaço</span><select value={place} disabled={busy||!!savedId||!!item} onChange={e=>setPlace(e.target.value)}>{memberAreas(me).map(a=><option key={a}>{a}</option>)}</select></label><label className="field"><span>O que falta ou precisa de atenção?</span><input autoFocus required minLength={2} maxLength={160} disabled={busy||!!savedId} value={title} placeholder="Ex.: falta detergente" onChange={e=>setTitle(e.target.value)}/></label><label className="field"><span>Fotografia · opcional</span><input type="file" accept="image/jpeg,image/png,image/webp" capture="environment" disabled={busy} onChange={e=>setPhoto(e.target.files?.[0]||null)}/></label><details><summary>Acrescentar uma nota</summary><textarea aria-label="Nota do problema" disabled={busy||!!savedId} maxLength={3000} value={note} onChange={e=>setNote(e.target.value)}/></details>{error&&<p role="alert" className="errorbox">{error}</p>}<button className="primary" disabled={busy}>{busy?'A guardar…':savedId?'Voltar a enviar fotografia':'Guardar para a gestão'}</button></form></DialogContent></Dialog>;
}
