'use client';
import {useState} from 'react';
import {Check,ChevronRight} from 'lucide-react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {areas,Data} from '@/lib/model';
type Props={draft:Data;team:{name:string}[];admin:boolean;today:string;onClose:()=>void;onSaved:(id:string,data:Data)=>Promise<void>;onDetails:(data:Data)=>void;onBusy?:(busy:boolean)=>void};
export function QuickTaskForm({draft,team,admin,today,onClose,onSaved,onDetails,onBusy}:Props){
 const [data,setData]=useState(draft),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const change=(key:keyof Data,value:string)=>setData(d=>({...d,[key]:value}));
 const tomorrow=new Date(Date.parse(today+'T12:00:00Z')+86400000).toISOString().slice(0,10);
 const submit=async(e:React.FormEvent)=>{e.preventDefault();if(busy)return;setBusy(true);onBusy?.(true);setError('');try{const r=await fetch('/api/records',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({kind:'task',data})});if(!r.ok){const text=await r.text();let message=text;try{message=JSON.parse(text).error||text;}catch{}throw new Error(message);}const p=await r.json() as {id:string};await onSaved(p.id,data);}catch(e){setError((e as Error).message);}finally{setBusy(false);onBusy?.(false);}};
 return <form onSubmit={submit} className="quick-task-form"><label className="field"><span>O que é preciso fazer?</span><input autoFocus required minLength={2} maxLength={160} value={data.title} onChange={e=>change('title',e.target.value)} placeholder="Ex.: marcar a limpeza do alojamento"/></label><div className="quick-task-fields"><label className="field"><span>Onde?</span><select value={data.area} onChange={e=>change('area',e.target.value)}>{areas.filter(a=>admin||a!=='Família').map(a=><option key={a}>{a}</option>)}</select></label><label className="field"><span>Quem trata?</span><select value={data.assignee} onChange={e=>change('assignee',e.target.value)} disabled={!admin}>{Array.from(new Set(['Por atribuir',...team.map(m=>m.name),data.assignee])).map(name=><option key={name}>{name}</option>)}</select></label></div><label className="field"><span>Quando? <small>Opcional</small></span><input type="date" value={data.due} onChange={e=>change('due',e.target.value)}/></label><div className="date-shortcuts">{[['Hoje',today],['Amanhã',tomorrow],['Sem prazo','']].map(([label,value])=><button type="button" key={label} aria-pressed={data.due===value} onClick={()=>change('due',value)}>{label}</button>)}</div><details className="quick-task-notes"><summary>Acrescentar uma nota</summary><textarea aria-label="Nota da tarefa" rows={3} maxLength={5000} value={data.description} onChange={e=>change('description',e.target.value)} placeholder="Informação útil para quem vai tratar…"/></details><button className="textbutton" type="button" disabled={busy} onClick={()=>onDetails(data)}>Mais detalhes e fotografia<ChevronRight size={17}/></button>{error&&<p className="errorbox" role="alert">{error}</p>}<div className="form-footer"><button type="button" className="secondary" disabled={busy} onClick={onClose}>Cancelar</button><button className="primary" disabled={busy}>{busy?'A guardar…':'Adicionar tarefa'}<Check size={17}/></button></div></form>;
}
export default function QuickTask(props:Props){const [busy,setBusy]=useState(false);return <Dialog open onOpenChange={v=>!v&&!busy&&props.onClose()}><DialogContent className="record-dialog quick-task-dialog" onInteractOutside={e=>e.preventDefault()}><DialogHeader><DialogTitle>Nova tarefa</DialogTitle><DialogDescription>Um assunto, um responsável. Os outros detalhes podem ficar para depois.</DialogDescription></DialogHeader><QuickTaskForm {...props} onBusy={setBusy}/></DialogContent></Dialog>;}
