'use client';
import {useState} from 'react';
import {requestJSON} from '@/lib/client-request';
import {Check,ChevronRight,Plus,X} from 'lucide-react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {areas,Data,Item,isOpen,mayUseArea,Member} from '@/lib/model';
import {templatesFor,templateDraft} from '@/lib/entry-templates';
type Props={draft:Data;team:(Partial<Member>&{name:string})[];allowedAreas?:readonly string[];admin:boolean;today:string;items?:Item[];onClose:()=>void;onSaved:(id:string,data:Data,item?:Item)=>Promise<void>;onDetails:(data:Data)=>void;onBusy?:(busy:boolean)=>void};
export function QuickTaskForm({draft,team,admin,today,items=[],onClose,onSaved,onDetails,onBusy,allowedAreas=areas}:Props){
 const [data,setData]=useState(draft),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const change=(key:keyof Data,value:string)=>setData(d=>({...d,[key]:value}));
 const setSteps=(steps:Data['steps'])=>setData(d=>({...d,steps,nextStep:steps.find(s=>!s.done)?.title||''}));
 const tomorrow=new Date(Date.parse(today+'T12:00:00Z')+86400000).toISOString().slice(0,10);
 const duplicates=items.filter(i=>i.kind==='task'&&isOpen(i)&&i.data.area===data.area&&i.data.title.trim().toLocaleLowerCase('pt-PT')===data.title.trim().toLocaleLowerCase('pt-PT'));
 const submit=async(e:React.FormEvent)=>{e.preventDefault();if(busy)return;if(data.repeat!=='Não repetir'&&!data.due){setError('Escolhe a primeira data para repetir esta tarefa.');return;}setBusy(true);onBusy?.(true);setError('');try{const p=await requestJSON<{id:string;item?:Item}>('/api/records',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({kind:'task',data})});await onSaved(p.id,data,p.item);}catch(e){setError((e as Error).message);}finally{setBusy(false);onBusy?.(false);}};
 return <form onSubmit={submit} className="quick-task-form">
  <label className="field"><span>O que é preciso fazer?</span><input autoFocus required minLength={2} maxLength={160} value={data.title} disabled={busy} onChange={e=>change('title',e.target.value)} placeholder="Escreve ou escolhe um modelo abaixo"/></label>
  <div className="quick-task-fields"><label className="field"><span>Onde?</span><select value={data.area} disabled={busy} onChange={e=>change('area',e.target.value)}>{areas.filter(a=>allowedAreas.includes(a)&&(admin||a!=='Família')).map(a=><option key={a}>{a}</option>)}</select></label><label className="field"><span>Quem trata?</span><select value={data.assignee} onChange={e=>change('assignee',e.target.value)} disabled={!admin||busy}>{Array.from(new Set(['Por atribuir',...team.filter(m=>m.role?mayUseArea(m as Member,data.area):true).map(m=>m.name),data.assignee])).map(name=><option key={name}>{name}</option>)}</select></label></div>
  {!data.title&&<section className="quick-templates" aria-label="Ideias para esta tarefa"><p>Ou começa por uma destas ideias</p><div>{templatesFor(data.area,'task',admin).map(t=><button type="button" disabled={busy} key={t.id} onClick={()=>setData(templateDraft(t,data,data.area))}>{t.label}<Plus size={15}/></button>)}</div></section>}
  <div className="quick-task-fields"><label className="field"><span>{data.repeat==='Não repetir'?'Quando?':'Primeira data'} {data.repeat==='Não repetir'&&<small>Opcional</small>}</span><input type="date" required={data.repeat!=='Não repetir'} disabled={busy} value={data.due} onChange={e=>change('due',e.target.value)}/></label><label className="field"><span>Repetição</span><select value={data.repeat} disabled={busy} onChange={e=>change('repeat',e.target.value)}>{['Não repetir','Diária','Semanal','Mensal'].map(r=><option key={r}>{r}</option>)}</select></label></div>
  <div className="date-shortcuts">{[['Hoje',today],['Amanhã',tomorrow],...(data.repeat==='Não repetir'?[['Sem prazo','']]:[])].map(([label,value])=><button type="button" key={label} disabled={busy} aria-pressed={data.due===value} onClick={()=>change('due',value)}>{label}</button>)}</div>
  {data.repeat!=='Não repetir'&&<p className="routine-help">Ao marcar como feita, é criada a próxima tarefa para {data.repeat==='Diária'?'o dia seguinte à data escolhida':data.repeat==='Semanal'?'7 dias depois da data escolhida':'o mês seguinte'}, com os passos por concluir.</p>}
  {data.steps.length>0&&<section className="quick-checklist" aria-label="Passos da tarefa"><h3>Lista de passos</h3><p>Ajusta o que queres incluir nesta visita.</p>{data.steps.map((step,n)=><div key={step.id}><span>{n+1}</span><input required maxLength={200} disabled={busy} aria-label={'Passo '+(n+1)} value={step.title} onChange={e=>setSteps(data.steps.map((s,k)=>k===n?{...s,title:e.target.value}:s))}/><button type="button" disabled={busy} aria-label={'Retirar passo '+(n+1)} onClick={()=>setSteps(data.steps.filter((_,k)=>k!==n))}><X size={18}/></button></div>)}</section>}
  {data.steps.length<30&&<button className="textbutton add-task-step" type="button" disabled={busy} onClick={()=>setSteps([...data.steps,{id:crypto.randomUUID(),title:'',done:false}])}><Plus size={16}/>Adicionar passo</button>}
  <details className="quick-task-notes"><summary>Acrescentar uma nota</summary><textarea aria-label="Nota da tarefa" disabled={busy} rows={3} maxLength={5000} value={data.description} onChange={e=>change('description',e.target.value)} placeholder="Informação útil para quem vai tratar…"/></details>
  <button className="textbutton" type="button" disabled={busy} onClick={()=>onDetails(data)}>Mais detalhes e fotografia<ChevronRight size={17}/></button>
  {duplicates.length>0&&<p className="routine-help" role="status">Já existe uma tarefa em aberto com este nome neste espaço. Confirma se precisas de outra antes de guardar.</p>}
  {error&&<p className="errorbox" role="alert">{error}</p>}<div className="form-footer"><button type="button" className="secondary" disabled={busy} onClick={onClose}>Cancelar</button><button className="primary" disabled={busy}>{busy?'A guardar…':'Adicionar tarefa'}<Check size={17}/></button></div>
 </form>;
}
export default function QuickTask(props:Props){const [busy,setBusy]=useState(false);return <Dialog open onOpenChange={v=>!v&&!busy&&props.onClose()}><DialogContent className="record-dialog quick-task-dialog" onInteractOutside={e=>e.preventDefault()}><DialogHeader><DialogTitle>Nova tarefa</DialogTitle><DialogDescription>Escolhe um modelo ou escreve a tua tarefa. Indica quem faz e quando.</DialogDescription></DialogHeader><QuickTaskForm {...props} onBusy={setBusy}/></DialogContent></Dialog>;}
