'use client';
import {useState} from 'react';
import {Item,isOpen,lodgingAreas} from '@/lib/model';
import {addDays} from '@/lib/family';
export default function ReservationsMonth({items,today,area,onOpen,onConnect}:{items:Item[];today:string;area:string;onOpen:(i:Item)=>void;onConnect:()=>void}){
 const [selected,setSelected]=useState('Todas');const end=addDays(today,29);
 const stays=items.filter(i=>i.kind==='stay'&&isOpen(i)&&i.data.due<=end&&i.data.checkout>=today&&(area==='Todas as áreas'||i.data.area===area)&&(selected==='Todas'||i.data.area===selected)).sort((a,b)=>a.data.due.localeCompare(b.data.due));
 return <section className="panel month-reservations"><div className="section-top"><div><h2>Os próximos 30 dias</h2><small>{today.split('-').reverse().join('/')} — {end.split('-').reverse().join('/')}</small></div><span className="badge">{stays.length} reservas</span></div><div className="talkguest-status"><div><strong>Talkguest · por ligar</strong><p>Este calendário mostra apenas reservas já guardadas na app.</p></div><button className="textbutton" onClick={onConnect}>Preparar ligação</button></div>{area==='Todas as áreas'&&<div className="scope-chips" aria-label="Filtrar alojamento">{['Todas',...lodgingAreas].map(a=><button key={a} aria-pressed={selected===a} onClick={()=>setSelected(a)}>{a}</button>)}</div>}{stays.length?<div className="reservation-cards">{stays.map(i=><button className="reservation-card" key={i.id} onClick={()=>onOpen(i)}><span>{i.data.area}</span><strong>{i.data.title}</strong><p>{i.data.due.split('-').reverse().join('/')} → {i.data.checkout.split('-').reverse().join('/')}</p><div className="reservation-flags"><span className={'badge '+(i.data.guestsConfirmed?'success':'waiting')}>{i.data.guestsConfirmed?'Hóspedes confirmados':'Confirmar hóspedes'}</span><span className={'badge '+(i.data.arrivalConfirmed?'success':'waiting')}>{i.data.arrivalConfirmed?`Chegada ${i.data.arrival}`:'Confirmar chegada'}</span><span className={'badge '+(i.data.cleaning==='Concluída'?'success':'waiting')}>Limpeza: {i.data.cleaning}</span></div></button>)}</div>:<p className="quiet-empty">Sem reservas registadas para este período. A disponibilidade não foi confirmada no Talkguest.</p>}</section>;
}
