'use client';
import {useState} from 'react';
import {Member,areas} from '@/lib/model';
import {Plus,Mail,ShieldCheck} from 'lucide-react';
type Person=Member&{invited_at?:string};
export default function Team({team,refresh}:{team:Person[];refresh:()=>Promise<void>}){
 const [editing,setEditing]=useState(false),[name,setName]=useState(''),[email,setEmail]=useState(''),[scope,setScope]=useState<string[]>([]),[active,setActive]=useState(true),[existing,setExisting]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('');
 const edit=(p?:Person)=>{setEditing(true);setName(p?.name||'');setEmail(p?.email||'');setScope(p?.allowed_areas||[]);setActive(p?.active!==false);setExisting(!!p);setMessage('');setError('');};
 async function save(action:'invite'|'save'){if(busy)return;setBusy(true);setError('');setMessage('');try{const r=await fetch('/api/team',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,email,allowed_areas:scope,active,action})});const text=await r.text();let data:any;try{data=JSON.parse(text);}catch{}await refresh();if(!r.ok)throw new Error(data?.error||text);setMessage(action==='invite'&&active?(data.delivery==='code'?'Já tinha conta: foi enviado um novo código de entrada por email.':'Convite enviado por email. Basta abrir e entrar.'):'Permissões guardadas.');setEditing(false);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <div className="team-simple"><section className="panel setup-card"><div className="section-top"><h2>Quem tem acesso</h2><button className="secondary" onClick={()=>edit()}><Plus size={18}/>Convidar</button></div>{team.map(p=><div className="team-person" key={p.email}><span className="avatar">{p.name.slice(0,1)}</span><div><strong>{p.name}</strong><small>{p.email}</small><p>{p.role==='admin'?'Gestão · todos os espaços':p.active===false?'Acesso suspenso':p.allowed_areas?.join(' · ')||'Sem espaços autorizados'}</p>{p.role==='employee'&&<small>{p.invite_status==='sent'?'Convite enviado':p.invite_status==='failed'?'Email por enviar':'Convite por enviar'}</small>}</div>{p.role==='employee'&&<button className="textbutton" onClick={()=>edit(p)}>Gerir</button>}</div>)}<p className="muted"><ShieldCheck size={16}/> Cada colaboradora vê as suas tarefas e ocorrências nos espaços escolhidos. A agenda dos miúdos fica só para a família.</p></section>{message&&<p className="notice" role="status">{message}</p>}{editing&&<form className="panel setup-card" onSubmit={e=>{e.preventDefault();void save(existing?'save':'invite');}}><h2>{existing?'Acesso da colaboradora':'Convidar uma colaboradora'}</h2><div className="form-grid"><label className="field"><span>Nome</span><input required minLength={2} maxLength={80} value={name} disabled={busy||existing} onChange={e=>setName(e.target.value)}/></label><label className="field"><span>Email para receber o convite</span><input type="email" required value={email} disabled={busy||existing} onChange={e=>setEmail(e.target.value)}/></label></div><fieldset className="scope-options"><legend>Onde vai trabalhar?</legend>{areas.filter(a=>a!=='Família').map(a=><label key={a}><input type="checkbox" checked={scope.includes(a)} disabled={busy} onChange={e=>setScope(e.target.checked?[...scope,a]:scope.filter(x=>x!==a))}/><span>{a}</span></label>)}</fieldset>{existing&&<label className="scope-option"><input type="checkbox" checked={active} disabled={busy} onChange={e=>setActive(e.target.checked)}/>Acesso ativo</label>}<div className="setup-actions"><button className="primary" disabled={busy||!scope.length}>{busy?'A tratar…':existing?'Guardar acesso':'Enviar convite'}<Mail size={17}/></button>{existing&&active&&<button type="button" className="secondary" disabled={busy||!scope.length} onClick={()=>void save('invite')}>Reenviar convite</button>}<button type="button" className="textbutton" disabled={busy} onClick={()=>setEditing(false)}>Cancelar</button></div>{error&&<p className="errorbox" role="alert">{error}</p>}</form>}</div>;
}
