'use client';
import {Proposal,proposalData} from '@/lib/assistant-ai';
import Assistant from './assistant';
import Notifications from './notifications';
import Setup from './setup';
import EmployeeDay from './employee-day';
import QuickReport from './quick-report';
import Team from './team';
import FamilyAgenda from './family-agenda';
import ReservationsMonth from './reservations-month';
import TalkguestConnection from './talkguest-connection';
import PushSettings,{pauseDevicePush} from './push-settings';
import CleaningPlanner from './cleaning-planner';
import TaskActions from './task-actions';
import FocusDay from './focus-day';
import SpaceCards from './space-cards';
import QuickTask from './quick-task';
import Login from './login';
import Account from './account';
import TemplateLibrary,{EntrySuggestions} from './entry-templates';
import {EntryTemplate,templateDraft} from '@/lib/entry-templates';
import {useEffect,useState,useCallback,useRef} from 'react';
import {LayoutTemplate,UserRound,LogIn,Trash2,Undo2,Ellipsis,Home,LayoutDashboard,CheckCheck,Camera,ShoppingBag,CalendarDays,Users,Plug,Plus,Search,ArrowUpRight,ArrowRight,Bell,Leaf,WashingMachine,House,ChevronRight,Clock,Check,ShieldCheck,FileText,Sparkles,RefreshCw,MapPin,BriefcaseBusiness} from 'lucide-react';
import {Sidebar,SidebarProvider,SidebarHeader,SidebarContent,SidebarFooter,SidebarGroup,SidebarGroupLabel,SidebarMenu,SidebarMenuItem,SidebarMenuButton,SidebarInset,SidebarTrigger} from '@/components/ui/sidebar';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Checkbox} from '@/components/ui/checkbox';
import {Toaster,toast} from 'sonner';
import {ARROIOS,isLodgingArea,areas,states,notices,Item,Data,canTrash,statusTone,memberAreas,mayUseArea} from '@/lib/model';
const navigation=[['overview','Hoje',CalendarDays],['spaces','Espaços',House],['more','Mais',Ellipsis],['history','Histórico',Clock],['task','Tarefas e agenda',CheckCheck],['incident','Ocorrências',Camera],['purchase','Compras',ShoppingBag],['stay','Alojamentos',House],['supplier','Contactos',BriefcaseBusiness],['notifications','Avisos',Bell],['trash','Lixo',Trash2],['assistant','Assistente',Sparkles],['templates','Modelos e rotinas',LayoutTemplate],['account','A minha conta',UserRound],['setup','Preparar a app',CheckCheck],['family','Agenda dos miúdos',CalendarDays],['team','Equipa',Users],['connections','Integrações',Plug]] as const;
const labels:Record<string,string>={task:'tarefa',incident:'ocorrência',purchase:'compra',supplier:'contacto',stay:'estadia'};
const initial:Data={deletedAt:'',nextStep:'',steps:[],waitingFor:'',reviewOn:'',snoozeUntil:'',supplierId:'',phone:'',email:'',serviceAreas:[],completedAt:'',title:'',area:'Limpeza da casa',description:'',status:'Por fazer',priority:'Normal',assignee:'Por atribuir',due:'',time:'',repeat:'Não repetir',accepted:false,price:null,url:'',contact:'',category:'',channel:'Manual',checkout:'',guests:1,confirmedGuests:null,guestsConfirmed:false,arrival:'',arrivalConfirmed:false,cleaning:'Por marcar',quotes:[]};
function Pick({label,value,options,onChange}:{label:string;value:string;options:readonly string[];onChange:(v:string)=>void}){return <label className="field"><span>{label}</span><Select value={value} onValueChange={onChange}><SelectTrigger className="w-full"><SelectValue/></SelectTrigger><SelectContent>{options.map(x=><SelectItem key={x} value={x}>{x}</SelectItem>)}</SelectContent></Select></label>;}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="field"><span>{label}</span>{children}</label>;}
function Toggle({label,value,onChange}:{label:string;value:boolean;onChange:(v:boolean)=>void}){return <label className="toggle"><Checkbox checked={value} onCheckedChange={x=>onChange(x===true)}/>{label}</label>;}
const euro=(n:number)=>new Intl.NumberFormat('pt-PT',{style:'currency',currency:'EUR'}).format(n);
const date=(s:string)=>s?new Date(s+'T12:00:00').toLocaleDateString('pt-PT',{day:'numeric',month:'short'}):'Sem prazo';
export default function Workspace({initialView='overview'}:{initialView?:string}){
 const [view,setView]=useState(initialView),[area,setArea]=useState('Todas as áreas'),[query,setQuery]=useState(''),[status,setStatus]=useState('Em aberto');
 const [items,setItems]=useState<Item[]>([]),[me,setMe]=useState<any>(null),[team,setTeam]=useState<any[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const [logoutBusy,setLogoutBusy]=useState(false);
 const [editing,setEditing]=useState<{kind:Item['kind'];id?:string;version?:number;data:Data}|null>(null),[saving,setSaving]=useState(false),[formError,setFormError]=useState('');
 const [files,setFiles]=useState<any[]>([]),[audit,setAudit]=useState<any[]>([]),[photo,setPhoto]=useState<File|null>(null),[detailError,setDetailError]=useState('');
 const [deletedItems,setDeletedItems]=useState<Item[]>([]),[deleting,setDeleting]=useState<Item|null>(null),[actionBusy,setActionBusy]=useState(false);
 const [adding,setAdding]=useState(false);
 const [templateFilter,setTemplateFilter]=useState<{area:string;kind:Item['kind']|'all'}>({area:'Todas as áreas',kind:'all'});
 const [quickTask,setQuickTask]=useState<Data|null>(null);
 const [reporting,setReporting]=useState<{area:string;item?:Item}|null>(null);
 const today=new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Lisbon',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
 const admin=me?.role==='admin';
 const allowedAreas=me?memberAreas(me):[];
 const loadSequence=useRef(0);
 const load=useCallback(async()=>{const sequence=++loadSequence.current;try{const r=await fetch('/api/records',{cache:'no-store'});if(sequence!==loadSequence.current)return;if(r.status===401||r.status===403){setItems([]);setDeletedItems([]);setMe(null);setTeam([]);setEditing(null);setQuickTask(null);setDeleting(null);setAdding(false);setReporting(null);setError(r.status===403?'Este email já não tem acesso. Entra com um email autorizado.':'');return;}if(!r.ok)throw new Error(r.status===403?await r.text():'Não foi possível carregar os dados. Tenta novamente.');const p:any=await r.json();if(sequence!==loadSequence.current)return;setItems(p.items);setDeletedItems(p.deletedItems||[]);setMe(p.member);setTeam(p.team);setEditing(current=>current&&mayUseArea(p.member,current.data.area)&&(!current.id||p.items.some((i:Item)=>i.id===current.id))?current:null);setQuickTask(current=>current&&mayUseArea(p.member,current.area)?current:null);setReporting(current=>current&&mayUseArea(p.member,current.area)?current:null);setArea(current=>current==='Todas as áreas'||mayUseArea(p.member,current)?current:'Todas as áreas');if(p.member.role!=='admin')setView(current=>['family','team','setup','connections','stay','supplier','purchase'].includes(current)?'overview':current);setError('');}catch(e){if(sequence===loadSequence.current)setError((e as Error).message);}finally{if(sequence===loadSequence.current)setLoading(false);}},[]);
 useEffect(()=>{if('serviceWorker' in navigator)navigator.serviceWorker.register('/sw.js').catch(()=>{});const requested=new URLSearchParams(window.location.search).get('view');if(requested&&['notifications','family'].includes(requested))setView(requested);load();const t=setInterval(load,60000);const visible=()=>{if(document.visibilityState==='visible')load();};window.addEventListener('focus',visible);document.addEventListener('visibilitychange',visible);return()=>{clearInterval(t);window.removeEventListener('focus',visible);document.removeEventListener('visibilitychange',visible);};},[load]);
 useEffect(()=>{const ctx=(document as any).modelContext;if(!ctx?.registerTool)return;const ac=new AbortController();Promise.resolve(ctx.registerTool({name:'list_household_items',description:'Ler os registos visíveis na app; não altera dados.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:async()=>{const r=await fetch('/api/records');if(!r.ok)throw new Error('Sem acesso aos registos');const p:any=await r.json();setItems(p.items);return {items:p.items};}},{signal:ac.signal})).catch(()=>{});Promise.resolve(ctx.registerTool({name:'start_household_incident',description:'Abrir o formulário de ocorrência com um título. Não guarda nem envia mensagens.',inputSchema:{type:'object',properties:{title:{type:'string',minLength:2,maxLength:160}},required:['title'],additionalProperties:false},execute:async(p:any)=>{if(typeof p.title!=='string'||p.title.trim().length<2||p.title.length>160)throw new Error('Título inválido');setEditing({kind:'incident',data:{...initial,title:p.title.trim()}});setFormError('');return {opened:true,saved:false};}},{signal:ac.signal})).catch(()=>{});return()=>ac.abort();},[]);
 const readDetails=async(id:string)=>{setDetailError('');try{const r=await fetch('/api/records?id='+encodeURIComponent(id));if(!r.ok)throw new Error('Não foi possível carregar fotografias e histórico.');const p:any=await r.json();setFiles(p.files);setAudit(p.audit);}catch(e){setDetailError((e as Error).message);}};
 const open=(i:Item)=>{setEditing({kind:i.kind,id:i.id,version:i.version,data:structuredClone(i.data)});setFormError('');setPhoto(null);setFiles([]);setAudit([]);readDetails(i.id);};
 const create=(kind:Item['kind'],a?:string)=>{a=allowedAreas.includes(a as Data['area'])?a:allowedAreas.includes(area as Data['area'])?area:allowedAreas[0];if(!a)return;if(kind==='stay'&&!isLodgingArea(a))a=ARROIOS;if(kind==='task'){setQuickTask({...initial,area:(a||(area!=='Todas as áreas'?area:'Limpeza da casa')) as Data['area'],assignee:me?.name||'Por atribuir',steps:[],quotes:[]});return;}setEditing({kind,data:{...initial,area:(a|| (kind==='stay'?ARROIOS:area!=='Todas as áreas'?area:'Limpeza da casa')) as any,assignee:!admin&&me?me.name:'Por atribuir',quotes:[]}});setFormError('');setPhoto(null);setFiles([]);setAudit([]);setDetailError('');};
 const chooseTemplate=(template:EntryTemplate,selected:string)=>{if(!me||(!admin&&!['task','incident'].includes(template.kind)))return;const data=templateDraft(template,{...initial,assignee:me.name},selected);if(!mayUseArea(me,data.area))return;if(template.kind==='task'){setQuickTask(data);return;}setEditing({kind:template.kind,data});setFormError('');setPhoto(null);setFiles([]);setAudit([]);setDetailError('');};
 const showTemplates=(selected='Todas as áreas',kind:Item['kind']|'all'='all')=>{setTemplateFilter({area:selected,kind});go('templates');};
 const reviewProposal=(a:Proposal)=>{const item=a.type==='updateTask'?items.find(i=>i.id===a.recordId):undefined;if(a.type==='updateTask'&&(!item||item.version!==a.version)){toast.error('A tarefa mudou entretanto. Pede uma proposta atualizada ao Assistente.');return;}setEditing({kind:'task',id:item?.id,version:item?.version,data:proposalData(a,item)});setFormError('');setPhoto(null);setFiles([]);setAudit([]);setDetailError('');if(item)readDetails(item.id);};
 const change=(key:keyof Data,value:any)=>setEditing(e=>e?{...e,data:{...e.data,[key]:value}}:e);
 const save=async(e:React.FormEvent)=>{
  e.preventDefault();if(!editing||saving)return;
  const finish=(e.nativeEvent as SubmitEvent).submitter?.getAttribute('value')==='done';
  const draft=finish?{...editing,data:{...editing.data,status:'Concluído' as const,steps:editing.data.steps.map(step=>({...step,done:true}))}}:editing;
  setSaving(true);setFormError('');
  try{
   const r=await fetch('/api/records',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(draft)});
   if(!r.ok){const t=await r.text();let msg=t;try{msg=JSON.parse(t).error||t;}catch{}throw new Error(msg);}
   const p:any=await r.json();setEditing({...draft,id:p.id,version:(draft.version||0)+1});
   if(photo){const f=new FormData();f.append('recordId',p.id);f.append('file',photo);const fr=await fetch('/api/files',{method:'POST',body:f});if(!fr.ok)throw new Error('Registo guardado; fotografia não enviada: '+await fr.text());setPhoto(null);}
   await load();setEditing(null);toast.success(finish?'Feita. Ficou guardada no Histórico.':'Guardado: '+draft.data.title,{action:{label:finish?'Ver histórico':'Ver na lista',onClick:()=>{go(finish?'history':draft.kind);setStatus(['Concluído','Cancelado'].includes(draft.data.status)?draft.data.status:'Em aberto');}}});
  }catch(e){setFormError((e as Error).message);await load();}finally{setSaving(false);}
 };
 const response=async(r:Response)=>{if(!r.ok){const text=await r.text();let message=text;try{message=JSON.parse(text).error||text;}catch{}throw new Error(message);}return r.json() as Promise<any>;};
 const updateItem=async(i:Item,patch:Partial<Data>)=>{if(actionBusy)return false;setActionBusy(true);try{await response(await fetch('/api/records',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:i.id,kind:i.kind,version:i.version,data:{...i.data,...patch}})}));await load();toast.success(patch.status==='Concluído'?'Feita. Ficou guardada no Histórico.':'Alteração guardada.');return true;}catch(e){toast.error((e as Error).message);await load();return false;}finally{setActionBusy(false);}};
 const complete=(i:Item)=>{void updateItem(i,{status:'Concluído',steps:i.data.steps.map(s=>({...s,done:true}))});};
 const restore=async(i:Item)=>{if(actionBusy)return;setActionBusy(true);try{await response(await fetch('/api/records',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:i.id,version:i.version,action:'restore'})}));await load();toast.success('Tarefa recuperada no seu espaço.');}catch(e){toast.error((e as Error).message);await load();}finally{setActionBusy(false);}};
 const askDelete=(i:Item)=>{setEditing(null);setDeleting(i);};
 const deleteTask=async()=>{if(!deleting||actionBusy)return;setActionBusy(true);const i=deleting;try{const result=await response(await fetch('/api/records',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:i.id,version:i.version})}));await load();setDeleting(null);toast.success('Tarefa movida para o lixo.',{duration:8000,action:{label:'Desfazer',onClick:()=>void restore({...i,version:result.version})}});}catch(e){setDeleting(null);toast.error((e as Error).message);await load();}finally{setActionBusy(false);}};
 const logout=async()=>{if(logoutBusy)return;setLogoutBusy(true);try{await pauseDevicePush();const r=await fetch('/api/auth/logout',{method:'POST'});if(!r.ok)throw new Error('Não foi possível terminar sessão. Tenta novamente.');++loadSequence.current;setItems([]);setDeletedItems([]);setMe(null);setTeam([]);setEditing(null);setQuickTask(null);setDeleting(null);setAdding(false);setReporting(null);setError('');window.location.assign('/login');}catch(e){toast.error(e instanceof Error?e.message:'Não foi possível terminar sessão.');}finally{setLogoutBusy(false);}};
 const active=items.filter(i=>i.kind!=='supplier'&&!['Concluído','Cancelado'].includes(i.data.status));const alerts=notices(items,today);
 const filtered=items.filter(i=>(view===i.kind||(i.kind!=='supplier'&&['overview','spaces','history'].includes(view)))&&(area==='Todas as áreas'||i.data.area===area||(i.kind==='supplier'&&i.data.serviceAreas.includes(area as any)))&&(!query||(i.data.title+' '+i.data.description+' '+i.data.assignee+' '+i.data.category+' '+i.data.phone+' '+i.data.email+' '+i.data.contact).toLowerCase().includes(query.toLowerCase()))&&(status==='Todos'||(status==='Em aberto'?!['Concluído','Cancelado'].includes(i.data.status):i.data.status===status)));
 const display=filtered.sort((a,b)=>view==='supplier'?a.data.title.localeCompare(b.data.title,'pt'):view==='history'?(b.data.completedAt||b.updated_at).localeCompare(a.data.completedAt||a.updated_at):(a.data.due||'9999').localeCompare(b.data.due||'9999'));
 const suppliers=items.filter(i=>i.kind==='supplier');
 const go=(v:string)=>{setView(v);setArea('Todas as áreas');setQuery('');setStatus('Em aberto');};
 const navigationVisible=navigation.filter(n=>(admin?['overview','family','spaces','assistant','more']:['overview','spaces','more']).includes(n[0]));
 const selectedNav=['overview','spaces','task','family','more'].includes(view)?view:['incident','purchase','stay'].includes(view)?'spaces':'more';
 const needs=active.filter(i=>alerts.some(a=>a.id===i.id));
 const upcoming=active.filter(i=>!needs.includes(i)&&i.data.due&&i.data.status!=='À espera').sort((a,b)=>a.data.due.localeCompare(b.data.due));
 const following=active.filter(i=>!needs.includes(i)&&!upcoming.includes(i));
 const group=(title:string,list:Item[],empty:string)=><section className="day-section"><div className="section-top"><h2>{title}</h2><span className="count">{list.length}</span></div><div className="panel">{list.length?list.map(row):<p className="quiet-empty">{empty}</p>}</div></section>;
 const row=(i:Item)=><div className="record-item" key={i.id}><button className="record-row" onClick={()=>open(i)}><span className={'row-icon '+i.kind}>{i.kind==='incident'?<Camera/>:i.kind==='purchase'?<ShoppingBag/>:i.kind==='stay'?<House/>:i.kind==='supplier'?<BriefcaseBusiness/>:<CheckCheck/>}</span><span className="row-main"><strong>{i.data.title}</strong><span>{i.data.area} <span className="separator">/</span> {i.kind==='supplier'?i.data.category||'Especialidade por indicar':i.kind==='stay'?`${i.data.guests} hóspedes · ${i.data.channel} · Limpeza: ${i.data.cleaning}`:i.data.assignee}{i.data.supplierId&&suppliers.find(s=>s.id===i.data.supplierId)?' · '+suppliers.find(s=>s.id===i.data.supplierId)!.data.title:''}</span></span><span className="row-end">{i.kind==='supplier'?<small>{i.data.phone||i.data.email||i.data.contact||'Abrir contacto'}</small>:<><span className={'badge '+(i.data.priority==='Urgente'?'urgent':statusTone(i.data.status))}>{i.data.status}</span><small className={i.data.due&&i.data.due<today&&!['Concluído','Cancelado'].includes(i.data.status)?'late':''}>{date(i.data.due)}{i.data.time?' · '+i.data.time:''}</small>{i.data.completedAt&&<small>Concluído · {date(i.data.completedAt.slice(0,10))}</small>}{i.data.price!==null&&<small>{euro(i.data.price)}</small>}</>}</span><ChevronRight size={17}/></button><TaskActions item={i} busy={actionBusy} onDone={complete} onDelete={me&&canTrash(i,me)?askDelete:undefined}/></div>;
 return <SidebarProvider><Toaster richColors position="top-center"/>{me&&<Sidebar><SidebarHeader><div className="brand"><span className="brandmark"><Home size={25}/></span><div>casa<span>em dia</span></div></div></SidebarHeader><SidebarContent><SidebarGroup><SidebarGroupLabel>O TEU ESPAÇO</SidebarGroupLabel><SidebarMenu>{navigationVisible.map(([id,label,Icon])=><SidebarMenuItem key={id}><SidebarMenuButton isActive={view===id} onClick={()=>go(id)} className="navbutton"><Icon/><span>{label}</span>{id==='incident'&&active.filter(i=>i.kind===id).length>0&&<b>{active.filter(i=>i.kind===id).length}</b>}</SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu></SidebarGroup><SidebarGroup><SidebarGroupLabel>OS TEUS ESPAÇOS</SidebarGroupLabel><SidebarMenu>{allowedAreas.map((a,index)=><SidebarMenuItem key={a}><SidebarMenuButton isActive={area===a} onClick={()=>{go('spaces');setArea(a);}} className="areabutton"><span className={'area-dot dot-'+areas.indexOf(a)}/><span>{a}</span></SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu></SidebarGroup></SidebarContent><SidebarFooter><button className="profile" onClick={()=>go('account')} aria-label="Abrir a minha conta"><span className="avatar">{me?.name?.slice(0,1)||'A'}</span><div><strong>{me?.name||'A tua família'}</strong><small>{admin?'Gestão e aprovações':me?'Tarefas e ocorrências':'Espaço privado'}</small></div><ChevronRight size={17}/></button></SidebarFooter></Sidebar>}<SidebarInset><header className="topbar"><div className="flex items-center gap-3"><span>{me?'Família & património':'Casa em Dia'}</span></div><div className="top-actions"><span className="private"><ShieldCheck size={15}/> Privado</span>{me?<button className="account-entry" onClick={()=>go('account')} aria-label="Abrir a minha conta"><span className="avatar">{me.name.slice(0,1)}</span>Conta</button>:<a className="account-entry" href="/login"><LogIn size={17}/>Entrar</a>}{me&&<button className="iconbutton" onClick={()=>go('notifications')} aria-label={'Ver avisos: '+new Set(alerts.map(a=>a.id)).size+' assuntos'}><Bell size={20}/>{alerts.length>0&&<b>{new Set(alerts.map(a=>a.id)).size}</b>}</button>}</div></header><main className="workspace">
 {!me?(loading?<div className="loading" role="status">A verificar a tua sessão…</div>:<section className="welcome-card login-card"><ShieldCheck size={34}/><h1>Entrar na Casa em Dia</h1><p>A tua família, casa e negócios, num só lugar.</p>{error&&<div className="errorbox" role="alert">{error}<button onClick={load}>Tentar novamente</button></div>}<Login onSuccess={()=>window.location.assign('/')}/></section>):<>
 <div className="page-heading"><div><p className="eyebrow">{new Date().toLocaleDateString('pt-PT',{weekday:'long',day:'numeric',month:'long',timeZone:'Europe/Lisbon'})}</p><h1>{view==='overview'?(admin?'Hoje':'O meu dia'):view==='spaces'&&area!=='Todas as áreas'?area:navigation.find(n=>n[0]===view)?.[1]}</h1><p>{view==='overview'?'Um dia mais leve começa aqui.':view==='spaces'?'Tudo o que acontece, no lugar certo.':view==='more'?'Pessoas, contactos e definições.':view==='history'?'Os assuntos que já ficaram resolvidos.':view==='incident'?'Do primeiro aviso até estar resolvido.':view==='stay'?'Hóspedes, chegadas e casas prontas a receber.':view==='task'?'Quem faz o quê, e quando.':view==='purchase'?'O que falta, quanto custa e quem trata.':view==='supplier'?'Os contactos certos, sempre à mão.':view==='assistant'?'Um próximo passo para cada assunto.':view==='notifications'?'O que precisa da tua atenção.':view==='trash'?'Tarefas apagadas, sempre recuperáveis.':view==='account'?'O teu acesso e a tua sessão.':view==='templates'?'Ideias prontas para transformar em tarefas reais.':view==='setup'?'Três passos para pôr o dia a dia a funcionar.':view==='family'?'Quem leva, quem busca e a que horas sair.':view==='team'?'Responsabilidades claras para cada pessoa.':'Liga os canais que já fazem parte do teu dia.'}</p></div>{admin&&!['family','assistant','notifications','trash','templates','account','team','setup','connections','more','history'].includes(view)&&<button className="primary" disabled={!me} onClick={()=>labels[view]?create(view as Item['kind']):create('task')}><Plus size={19}/>Adicionar</button>}</div>
 {error&&<div className="errorbox" role="alert">{error}<button onClick={load}>Tentar novamente</button></div>}
 {loading?<div className="loading">A carregar o teu espaço…</div>:!me?null:<>
 {view==='overview'&&admin&&(!team.some(m=>m.role==='employee')||!items.some(i=>i.kind==='task'&&i.data.repeat!=='Não repetir'))&&<button className="attention-banner setup-banner" onClick={()=>go('setup')}><CheckCheck size={21}/><span><strong>Vamos preparar o dia a dia?</strong><small>Equipa, rotinas e avisos no telemóvel</small></span><ChevronRight size={18}/></button>}
 {view==='overview'&&admin&&alerts.length>0&&<button className="attention-banner" onClick={()=>go('notifications')}><Bell size={21}/><span><strong>{new Set(alerts.map(a=>a.id)).size} {new Set(alerts.map(a=>a.id)).size===1?'assunto precisa':'assuntos precisam'} de atenção</strong><small>Ver prazos, decisões e chegadas</small></span><ChevronRight size={18}/></button>}
 {view==='overview'&&admin&&<FamilyAgenda team={team} compact onAll={()=>go('family')}/>}
 {view==='overview'&&admin&&<SpaceCards items={items} admin={admin} allowedAreas={allowedAreas} today={today} onOpen={a=>{go('spaces');setArea(a);}} onAdd={a=>create('task',a)}/>}
 {view==='overview'&&!admin&&<EmployeeDay items={items} me={me} today={today} busy={actionBusy} complete={complete} open={open} report={(area,item)=>setReporting({area,item})} history={()=>{go('history');setStatus('Concluído');}}/>}
 {view==='overview'&&admin&&<FocusDay items={items} me={me} today={today} initial={initial} refresh={load} open={open} create={create} remove={askDelete} canRemove={i=>canTrash(i,me)}/>}
 {view==='spaces'&&area==='Todas as áreas'&&<SpaceCards items={items} admin={admin} allowedAreas={allowedAreas} today={today} onOpen={a=>{setArea(a);setQuery('');setStatus('Em aberto');}} onAdd={a=>create('task',a)}/>}
 {view==='spaces'&&area==='Família'&&admin&&<FamilyAgenda team={team}/>}
 {view==='spaces'&&area!=='Todas as áreas'&&<button className="back-link" onClick={()=>setArea('Todas as áreas')}>‹ Todos os espaços</button>}

 {view==='spaces'&&area!=='Todas as áreas'&&<div className="space-actions"><button className="primary" onClick={()=>create('task',area)}><Plus size={18}/>Nova tarefa</button><button className="secondary" onClick={()=>admin?create('incident',area):setReporting({area})}><Camera size={18}/>Reportar problema</button>{admin&&isLodgingArea(area)&&<button className="secondary" onClick={()=>create('stay',area)}><House size={18}/>Nova estadia</button>}</div>}
 {admin&&((view==='spaces'&&area!=='Todas as áreas')||['task','incident','purchase','stay','supplier'].includes(view))&&<EntrySuggestions area={area} kind={view==='spaces'?'all':view as Item['kind']} admin={admin} onChoose={chooseTemplate} onAll={()=>showTemplates(area,view==='spaces'?'all':view as Item['kind'])}/>}
 {view==='templates'&&<TemplateLibrary key={templateFilter.area+templateFilter.kind} area={templateFilter.area} kind={templateFilter.kind} admin={admin} allowedAreas={allowedAreas} onChoose={chooseTemplate} onBlank={create}/>}
 {admin&&(view==='stay'||(view==='spaces'&&isLodgingArea(area)))&&<ReservationsMonth items={items} today={today} area={area} onOpen={open} onConnect={()=>go('connections')}/>}
 {admin&&(view==='stay'||(view==='spaces'&&isLodgingArea(area)))&&<div className="stay-summary">{[['Entradas hoje',active.filter(i=>i.kind==='stay'&&i.data.due===today&&(area==='Todas as áreas'||i.data.area===area))],['Saídas hoje',active.filter(i=>i.kind==='stay'&&i.data.checkout===today&&(area==='Todas as áreas'||i.data.area===area))],['Limpeza por concluir',active.filter(i=>i.kind==='stay'&&i.data.checkout>=today&&i.data.cleaning!=='Concluída'&&(area==='Todas as áreas'||i.data.area===area))]].map(([title,list])=><details className="panel" key={title as string}><summary><span>{title as string}</span><strong>{(list as Item[]).length}</strong></summary>{(list as Item[]).length?(list as Item[]).map(row):<p className="quiet-empty">Sem registos.</p>}</details>)}</div>}
 {view==='more'&&<section className="panel menu-list">{navigation.filter(n=>(admin||['task','incident','templates','account','history','assistant','notifications','trash'].includes(n[0]))&&['setup','family','task','incident','purchase','stay','supplier','assistant','notifications','trash','templates','account','team','history','connections'].includes(n[0])).map(([id,label,Icon])=><button key={id} className="space-row" onClick={()=>{if(id==='templates')showTemplates();else go(id);if(id==='history')setStatus('Concluído');}}><Icon size={22}/><span><strong>{label}</strong></span><ChevronRight size={18}/></button>)}</section>}
 {(['task','incident','purchase','stay','supplier','history'].includes(view)||(view==='spaces'&&area!=='Todas as áreas'))&&<section className="panel list-panel"><div className="section-top"><h2>{view==='spaces'?'Neste espaço':view==='history'?'Histórico':view==='task'?'Agenda de trabalho':view==='stay'?'Reservas e preparação':'Registos'} <span className="count">{display.length}</span></h2></div><div className="filters"><label className="search"><Search size={18}/><input placeholder="Procurar nos registos…" value={query} onChange={e=>setQuery(e.target.value)} aria-label="Procurar registos"/></label><Pick label="Área" value={area} options={['Todas as áreas',...allowedAreas]} onChange={setArea}/><Pick label="Estado" value={status} options={['Em aberto','Todos',...states]} onChange={setStatus}/></div>{display.length?display.map(row):<div className="empty"><FileText size={32}/><h3>{items.length?'Não há registos com estes filtros':'Vamos tirar as coisas da cabeça?'}</h3><p>{items.length?'Altera os filtros ou acrescenta um registo.':'Guarda o primeiro assunto, atribui um responsável e define o próximo passo.'}</p><button className="secondary" onClick={()=>create((labels[view]?view:'task') as any)}><Plus size={16}/>Adicionar {labels[view]||'tarefa'}</button></div>}</section>}
 {view==='spaces'&&area!=='Todas as áreas'&&admin&&<details className="space-extras"><summary>Contactos e histórico deste espaço</summary><section className="day-section"><div className="section-top"><h2>Contactos deste espaço</h2><button className="textbutton" onClick={()=>create('supplier')}><Plus size={17}/>Contacto</button></div><div className="panel">{suppliers.filter(i=>i.data.area===area||i.data.serviceAreas.includes(area as any)).length?suppliers.filter(i=>i.data.area===area||i.data.serviceAreas.includes(area as any)).map(row):<p className="quiet-empty">Adiciona quem trata da limpeza, manutenção ou assistência.</p>}</div><button className="textbutton" onClick={()=>{const a=area;go('history');setArea(a);setStatus('Concluído');}}>Ver histórico deste espaço <ArrowRight size={16}/></button></section></details>}
 {view==='assistant'&&<Assistant items={items} today={today} me={me} busy={actionBusy} open={open} update={updateItem} onProposal={reviewProposal}/>}
 {view==='notifications'&&<PushSettings/>}
 {view==='notifications'&&<Notifications items={items} today={today} name={me.name} open={open} refresh={load}/>}
 {view==='trash'&&<section className="panel">{deletedItems.length?deletedItems.map(i=><div className="trash-row" key={i.id}><Trash2 size={21}/><div><strong>{i.data.title}</strong><p>{i.data.area} · {i.data.assignee}</p><small>Apagada em {new Date(i.data.deletedAt).toLocaleDateString('pt-PT',{timeZone:'Europe/Lisbon'})}</small></div><button className="secondary" disabled={actionBusy} onClick={()=>restore(i)}><Undo2 size={16}/>Recuperar</button></div>):<div className="empty"><Trash2 size={32}/><h3>O lixo está vazio</h3><p>Quando apagas uma tarefa, podes recuperá-la aqui, com os detalhes e o histórico.</p></div>}</section>}

 {view==='setup'&&admin&&<Setup team={team} items={items} initial={initial} onTeam={()=>go('team')} onDraft={setQuickTask} onOpen={open}/>}
 {view==='account'&&<PushSettings/>}
 {view==='account'&&<Account member={me} busy={logoutBusy} onLogout={logout}/>}
 {view==='connections'&&admin&&<><TalkguestConnection/><div className="notice"><Plug size={21}/><div><strong>O registo manual já está disponível</strong><p>Nenhuma conta externa está ligada. As reservas e mensagens não são importadas nem enviadas automaticamente.</p></div></div><div className="integration-grid">{[['WhatsApp Business','Fotografias da empregada, pedidos e conversas com hóspedes.','É necessário definir o número e autorizar a ligação à plataforma WhatsApp Business.'],['Talkguest','Reservas, datas e informação da estadia.','É necessário confirmar os acessos e os dados disponibilizados pelo Talkguest.'],['Booking · Airbnb · Trip.com','Histórico de mensagens e dados em falta.','É necessário validar cada integração para evitar mensagens duplicadas.'],['Pesquisa na Internet','Comparação de preços e procura de prestadores.','A IA do Assistente já conversa sobre os teus registos. A pesquisa na Internet ainda precisa de ligação.']].map(([name,desc,next])=><article className="panel connection" key={name}><Plug size={24}/><span className="badge">Por ligar</span><h2>{name}</h2><p>{desc}</p><div className="connection-next">{next}</div></article>)}</div></>}
 {view==='team'&&admin&&<Team team={team} refresh={load}/>}
 {view==='family'&&admin&&<FamilyAgenda team={team}/>}
 </>}
 <footer className="page-footer"><span>Casa em Dia</span><span>Lisboa · Arruda dos Vinhos</span><button onClick={load}><RefreshCw size={14}/>Atualizar</button></footer>
 </>}
 </main></SidebarInset>
 {quickTask&&<QuickTask draft={quickTask} items={items} team={team} admin={admin} allowedAreas={allowedAreas} today={today} onClose={()=>setQuickTask(null)} onDetails={data=>{setQuickTask(null);setEditing({kind:'task',data});setFormError('');setPhoto(null);setFiles([]);setAudit([]);setDetailError('');}} onSaved={async(id,data)=>{setQuickTask(null);await load();toast.success('Tarefa adicionada em '+data.area,{action:{label:'Ver tarefas',onClick:()=>{go('task');setArea(data.area);}}});}}/>}
 {reporting&&me&&<QuickReport {...reporting} me={me} today={today} onClose={()=>setReporting(null)} onSaved={async()=>{setReporting(null);await load();toast.success('Registado para a gestão.');}}/>}
 {me&&<nav className="bottom-nav" aria-label="Navegação principal">{(admin?[['overview','Hoje',CalendarDays],['spaces','Espaços',House],['add','Adicionar',Plus],['family','Miúdos',Users],['more','Mais',Ellipsis]]:[['overview','O meu dia',CalendarDays],['spaces','Espaços',House],['add','Reportar',Camera],['more','Mais',Ellipsis]]).map(([id,label,Icon]:any)=><button key={id} aria-current={selectedNav===id?'page':undefined} className={id==='add'?'nav-add':''} onClick={()=>id==='add'?(admin?setAdding(true):allowedAreas.length&&setReporting({area:allowedAreas[0]})):go(id)}><Icon size={23}/><span>{label}</span></button>)}</nav>}
 <Dialog open={!!deleting} onOpenChange={v=>{if(!v&&!actionBusy)setDeleting(null);}}><DialogContent className="record-dialog delete-dialog"><DialogHeader><DialogTitle>Apagar esta tarefa?</DialogTitle><DialogDescription>“{deleting?.data.title}” deixa de aparecer nas listas e nos avisos. Podes recuperá-la em Mais → Lixo, com os detalhes e o histórico.</DialogDescription></DialogHeader><div className="form-footer"><button className="secondary" disabled={actionBusy} onClick={()=>setDeleting(null)}>Manter tarefa</button><button className="danger-button" disabled={actionBusy} onClick={deleteTask}><Trash2 size={17}/>{actionBusy?'A apagar…':'Apagar tarefa'}</button></div></DialogContent></Dialog>
 <Dialog open={adding} onOpenChange={setAdding}><DialogContent className="add-dialog"><DialogHeader><DialogTitle>O que vamos organizar?</DialogTitle><DialogDescription>Escolhe o assunto. Os detalhes vêm a seguir.</DialogDescription></DialogHeader><div className="menu-list"><button className="space-row" onClick={()=>{setAdding(false);showTemplates(area);}}><LayoutTemplate size={23}/><span><strong>Modelos e rotinas</strong><small>Limpeza, família e gestão dos espaços</small></span><ChevronRight size={18}/></button>{[['task','Uma tarefa',CheckCheck,'Combinar quem faz e quando'],['incident','Algo para arranjar',Camera,'Reportar e juntar fotografias'],...(admin?[['purchase','Uma compra',ShoppingBag,'Guardar o que falta'],['stay','Uma estadia',House,'Preparar hóspedes e chegada'],['supplier','Um contacto',BriefcaseBusiness,'Limpeza, manutenção e outros serviços']]:[])].map(([id,title,Icon,desc]:any)=><button className="space-row" key={id} onClick={()=>{setAdding(false);create(id);}}><Icon size={23}/><span><strong>{title}</strong><small>{desc}</small></span><ChevronRight size={18}/></button>)}</div></DialogContent></Dialog>
 <Dialog open={!!editing} onOpenChange={v=>{if(!v&&!saving)setEditing(null);}}><DialogContent className="record-dialog"><DialogHeader><p className="eyebrow">{editing?.id?'EM ACOMPANHAMENTO':'UM ASSUNTO DE CADA VEZ'}</p><DialogTitle>{editing?.id?'Editar':'Adicionar'} {labels[editing?.kind||'task']}</DialogTitle><DialogDescription>{editing?.kind==='stay'?'Confirma a ocupação e a chegada antes de preparar a casa.':'Guarda os detalhes e combina o próximo passo.'}</DialogDescription></DialogHeader>{editing&&<form onSubmit={save} className="record-form"><Field label={editing.kind==='supplier'?'Nome do prestador':editing.kind==='stay'?'Hóspede / referência da reserva':'O que é preciso fazer?'}><input required minLength={2} maxLength={160} value={editing.data.title} onChange={e=>change('title',e.target.value)} placeholder={editing.kind==='incident'?'Ex.: Torneira a pingar na cozinha':'Dá um nome a este assunto'}/></Field><div className="form-grid"><Pick label="Área" value={editing.data.area} options={editing.kind==='stay'?areas.filter(a=>isLodgingArea(a)):allowedAreas} onChange={v=>change('area',v)}/>{editing.kind!=='supplier'&&<Pick label="Responsável" value={editing.data.assignee} options={Array.from(new Set(['Por atribuir',...team.filter(x=>mayUseArea(x,editing.data.area)).map(x=>x.name),editing.data.assignee]))} onChange={v=>change('assignee',v)}/>}</div><Field label="Descrição e próximo passo"><textarea rows={3} maxLength={5000} value={editing.data.description} onChange={e=>change('description',e.target.value)} placeholder="O que aconteceu, o que falta e o que já foi tentado…"/></Field>
 {editing.kind!=='supplier'&&<section className="subsection"><h3>Um passo de cada vez</h3><Field label="Próximo passo concreto"><input maxLength={300} value={editing.data.nextStep} onChange={e=>change('nextStep',e.target.value)} placeholder="Ex.: telefonar ao técnico para marcar a visita"/></Field>{editing.data.steps.map((step,n)=><div className="step-edit" key={step.id}><Checkbox aria-label={'Concluir '+step.title} checked={step.done} onCheckedChange={v=>change('steps',editing.data.steps.map((s,k)=>k===n?{...s,done:v===true}:s))}/><input aria-label={'Passo '+(n+1)} required maxLength={200} value={step.title} onChange={e=>change('steps',editing.data.steps.map((s,k)=>k===n?{...s,title:e.target.value}:s))}/><button type="button" className="textbutton" onClick={()=>change('steps',editing.data.steps.filter((_,k)=>k!==n))}>Retirar</button></div>)}{editing.data.steps.length<30&&<button type="button" className="textbutton" onClick={()=>change('steps',[...editing.data.steps,{id:crypto.randomUUID(),title:'',done:false}])}><Plus size={16}/>Adicionar passo</button>}{editing.data.status==='À espera'&&<div className="form-grid"><Field label="À espera de quem?"><input maxLength={150} value={editing.data.waitingFor} onChange={e=>change('waitingFor',e.target.value)}/></Field><Field label="Voltar a verificar em"><input type="date" value={editing.data.reviewOn} onChange={e=>change('reviewOn',e.target.value)}/></Field></div>}{editing.data.snoozeUntil&&<Field label="Volta ao foco em (não altera o prazo)"><input type="date" value={editing.data.snoozeUntil} onChange={e=>change('snoozeUntil',e.target.value)}/></Field>}</section>}
 {editing.kind!=='supplier'&&admin&&<section className="subsection"><h3>Quem vai tratar?</h3><Field label="Contacto / prestador"><Select value={editing.data.supplierId||'none'} onValueChange={v=>change('supplierId',v==='none'?'':v)}><SelectTrigger className="w-full"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="none">Sem contacto associado</SelectItem>{suppliers.map(s=><SelectItem key={s.id} value={s.id}>{s.data.title} · {s.data.category||s.data.area}</SelectItem>)}</SelectContent></Select></Field><small>O responsável acompanha o assunto. O prestador é quem executa o serviço. Associar não envia um pedido.</small>{['task','incident'].includes(editing.kind)&&<Field label="Custo da intervenção (€)"><input type="number" min="0" max="1000000" step="0.01" value={editing.data.price??''} onChange={e=>change('price',e.target.value?Number(e.target.value):null)}/></Field>}</section>}
 {editing.kind==='supplier'&&<section className="subsection"><h3>Dados de contacto</h3><div className="form-grid"><Field label="Telefone"><input type="tel" maxLength={40} value={editing.data.phone} onChange={e=>change('phone',e.target.value)} placeholder="+351 …"/></Field><Field label="Email"><input type="email" maxLength={200} value={editing.data.email} onChange={e=>change('email',e.target.value)}/></Field></div><div className="contact-actions">{editing.data.phone&&<a className="secondary" href={'tel:'+editing.data.phone.replace(/[^+0-9]/g,'')}>Telefonar</a>}{editing.data.email&&<a className="secondary" href={'mailto:'+editing.data.email}>Escrever email</a>}</div><h3>Também trabalha nestes espaços</h3><div className="contact-areas">{areas.filter(a=>a!==editing.data.area).map(a=><Toggle key={a} label={a} value={editing.data.serviceAreas.includes(a)} onChange={v=>change('serviceAreas',v?[...editing.data.serviceAreas,a]:editing.data.serviceAreas.filter(x=>x!==a))}/>)}</div><small>O espaço principal é o indicado no campo Área.</small>{editing.id&&<><h3 className="contact-history-title">Trabalhos associados</h3><small>Inclui assuntos em aberto e concluídos, com os custos e as notas registadas.</small><div className="contact-history">{items.filter(i=>i.data.supplierId===editing.id).length?items.filter(i=>i.data.supplierId===editing.id).sort((a,b)=>b.updated_at.localeCompare(a.updated_at)).map(i=><div key={i.id}><strong>{i.data.title}</strong><p>{i.data.area} · {i.data.status}{i.data.price!==null?' · '+euro(i.data.price):''}</p><small>{i.data.completedAt?'Concluído em '+date(i.data.completedAt.slice(0,10)):'Prazo: '+date(i.data.due)}</small><p>{i.data.description}</p></div>):<p className="quiet-empty">Ao associar este contacto a uma tarefa ou ocorrência, o trabalho fica aqui registado.</p>}</div></>}</section>}
 {editing.kind!=='supplier'&&<><div className="form-grid"><Pick label="Estado" value={editing.data.status} options={admin?states:states.filter(s=>s!=='Aprovado')} onChange={v=>change('status',v)}/><Pick label="Prioridade" value={editing.data.priority} options={['Normal','Alta','Urgente']} onChange={v=>change('priority',v)}/><Field label={editing.kind==='stay'?'Entrada':'Prazo'}><input type="date" required={editing.kind==='stay'||(editing.kind==='task'&&editing.data.repeat!=='Não repetir')} value={editing.data.due} onChange={e=>change('due',e.target.value)}/></Field>{editing.kind==='stay'?<Field label="Saída"><input type="date" required min={editing.data.due} value={editing.data.checkout} onChange={e=>change('checkout',e.target.value)}/></Field>:<Field label="Hora (opcional)"><input type="time" value={editing.data.time} onChange={e=>change('time',e.target.value)}/></Field>}</div></>}
 {editing.kind==='task'&&editing.data.stayId&&<p className="notice compact">Esta limpeza está ligada a uma estadia. Ao concluir, a preparação do alojamento é atualizada.</p>}
 {editing.kind==='stay'&&admin&&editing.id&&items.find(i=>i.id===editing.id)&&<CleaningPlanner key={editing.id} stay={items.find(i=>i.id===editing.id)!} items={items} team={team} onSaved={async()=>{await load();setEditing(null);toast.success('Limpezas preparadas. Já aparecem nas tarefas da equipa.');}}/>}
 {editing.kind==='task'&&<><Pick label="Repetição após conclusão" value={editing.data.repeat} options={['Não repetir','Diária','Semanal','Mensal']} onChange={v=>change('repeat',v)}/><Toggle label="Responsável confirmou que assume a tarefa" value={editing.data.accepted} onChange={v=>change('accepted',v)}/></>}
 {editing.kind==='stay'&&<div className="subsection"><h3>Preparar a chegada</h3><div className="form-grid"><Pick label="Origem da reserva" value={editing.data.channel} options={['Manual','Booking','Airbnb','Trip.com','Talkguest']} onChange={v=>change('channel',v)}/><Field label="Hóspedes na reserva"><input type="number" min="1" max="100" required value={editing.data.guests} onChange={e=>change('guests',Number(e.target.value))}/></Field><Field label="Hóspedes confirmados"><input type="number" min="1" max="100" value={editing.data.confirmedGuests??''} onChange={e=>change('confirmedGuests',e.target.value?Number(e.target.value):null)}/></Field><Field label="Hora prevista de chegada"><input type="time" value={editing.data.arrival} onChange={e=>change('arrival',e.target.value)}/></Field>{editing.data.cleaningManaged?<div className="field"><span>Limpeza</span><strong>{editing.data.cleaning}</strong><small>Atualizada pelas tarefas ligadas.</small></div>:<Pick label="Limpeza" value={editing.data.cleaning} options={['Por marcar','Marcada','Concluída']} onChange={v=>change('cleaning',v)}/>}</div><Toggle label="Número de hóspedes confirmado por mensagem" value={editing.data.guestsConfirmed} onChange={v=>change('guestsConfirmed',v)}/><Toggle label="Hora de chegada confirmada por mensagem" value={editing.data.arrivalConfirmed} onChange={v=>change('arrivalConfirmed',v)}/>{editing.data.confirmedGuests&&editing.data.confirmedGuests!==editing.data.guests?<p className="errorbox">O número confirmado difere da reserva. Valida as condições antes de aceitar.</p>:null}<button type="button" className="secondary" onClick={async()=>{const d=editing.data;const msg=`Olá! Para prepararmos a sua estadia, ${!d.guestsConfirmed?'pode confirmar o total de adultos, crianças e bebés? ':''}${!d.arrivalConfirmed?'Qual é a hora prevista de chegada? ':''}Se precisar de berço ou de uma distribuição específica de camas, diga-nos, por favor. Obrigada!`;try{await navigator.clipboard.writeText(msg);toast.success('Mensagem copiada. Não foi enviada.');}catch{toast.error('Não foi possível copiar neste navegador.');}}}>Copiar pedido de confirmação</button><small>Revê o histórico da plataforma antes de enviar. A app ainda não tem acesso às mensagens.</small></div>}
 {['purchase','supplier'].includes(editing.kind)&&<div className="form-grid">{editing.kind==='purchase'&&<Field label="Preço total (€), incluindo entrega"><input type="number" min="0" step="0.01" value={editing.data.price??''} onChange={e=>change('price',e.target.value?Number(e.target.value):null)}/></Field>}<Field label={editing.kind==='supplier'?'Especialidade':'Produto / referência'}><input value={editing.data.category} onChange={e=>change('category',e.target.value)}/></Field><Field label="Contacto"><input value={editing.data.contact} onChange={e=>change('contact',e.target.value)}/></Field><Field label="Página do produto ou prestador"><input type="url" placeholder="https://" value={editing.data.url} onChange={e=>change('url',e.target.value)}/></Field></div>}
 {['incident','purchase'].includes(editing.kind)&&admin&&<div className="subsection"><div className="section-top"><h3>Propostas para decidir</h3><button className="textbutton" type="button" onClick={()=>change('quotes',[...editing.data.quotes,{id:crypto.randomUUID(),supplier:'',amount:0,notes:'',url:'',selected:false}])}><Plus size={16}/>Proposta</button></div><p className="muted">Regista preços verificados. Aprovar aqui não contrata nem efetua pagamentos.</p>{editing.data.quotes.map((q,idx)=><div className={'quote '+(q.selected?'chosen':'')} key={q.id}><div className="form-grid"><Field label="Fornecedor / prestador"><input required value={q.supplier} onChange={e=>change('quotes',editing.data.quotes.map((x,n)=>n===idx?{...x,supplier:e.target.value}:x))}/></Field><Field label="Total (€)"><input required type="number" min="0" step="0.01" value={q.amount} onChange={e=>change('quotes',editing.data.quotes.map((x,n)=>n===idx?{...x,amount:Number(e.target.value)}:x))}/></Field></div><Field label="Prazo, disponibilidade e condições"><input value={q.notes} onChange={e=>change('quotes',editing.data.quotes.map((x,n)=>n===idx?{...x,notes:e.target.value}:x))}/></Field><Field label="Fonte / orçamento online"><input type="url" placeholder="https://" value={q.url} onChange={e=>change('quotes',editing.data.quotes.map((x,n)=>n===idx?{...x,url:e.target.value}:x))}/></Field><div className="flex gap-4"><button type="button" className="textbutton" onClick={()=>{setEditing({...editing,data:{...editing.data,status:'Aprovado',quotes:editing.data.quotes.map((x,n)=>({...x,selected:n===idx}))}});}}>{q.selected?<><Check size={16}/>Escolhida · {euro(q.amount)}</>:'Escolher proposta'}</button><button type="button" className="textbutton muted" onClick={()=>change('quotes',editing.data.quotes.filter((_,n)=>n!==idx))}>Retirar</button></div></div>)}<a className="secondary" target="_blank" rel="noopener noreferrer" href={'https://www.google.com/search?q='+encodeURIComponent(editing.data.title+' '+(editing.data.area==='Quinta · Arruda'?'Arruda dos Vinhos':'Lisboa')+' preços')}><Search size={16}/>Pesquisar na web <ArrowUpRight size={15}/></a><small>Abre uma pesquisa para ti. O agente de pesquisa autónoma ainda não está ligado.</small></div>}
 {['incident','task','purchase'].includes(editing.kind)&&<div className="subsection"><h3>Fotografias</h3><Field label="JPG, PNG ou WebP · até 10 MB"><input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>setPhoto(e.target.files?.[0]||null)}/></Field>{photo&&<p className="muted">{photo.name} · será enviada ao guardar</p>}<div className="photo-grid">{files.map(f=><a target="_blank" rel="noopener noreferrer" key={f.id} href={'/api/files?id='+f.id}><img alt={f.name} src={'/api/files?id='+f.id}/></a>)}</div><small>As imagens ficam associadas ao registo. A interpretação automática ainda não está ligada.</small></div>}
 {detailError&&<div className="errorbox">{detailError}<button type="button" onClick={()=>editing.id&&readDetails(editing.id)}>Tentar novamente</button></div>}
 {audit.length>0&&<details className="history"><summary>Histórico · {audit.length} ações</summary>{audit.map(a=><p key={a.id}><strong>{a.action}</strong><br/>{a.actor} · {new Date(a.at).toLocaleString('pt-PT')}</p>)}</details>}
 {formError&&<div className="errorbox" role="alert">{formError}</div>}<div className="form-footer">{editing.id&&items.find(i=>i.id===editing.id)&&canTrash(items.find(i=>i.id===editing.id)!,me)&&<button type="button" className="delete-button" disabled={saving||actionBusy} onClick={()=>askDelete(items.find(i=>i.id===editing.id)!)}><Trash2 size={17}/>Apagar</button>}<button type="button" className="secondary" disabled={saving} onClick={()=>setEditing(null)}>Cancelar</button>{editing.id&&editing.kind==='task'&&!['Concluído','Cancelado'].includes(editing.data.status)&&<button type="submit" value="done" className="done-button" disabled={saving}><Check size={17}/>Feita</button>}<button className="primary" disabled={saving}>{saving?'A guardar…':'Guardar alterações'}<Check size={17}/></button></div></form>}</DialogContent></Dialog>
 </SidebarProvider>;
}
