import {DUPLEX,ALFAMA} from './model';
import type {EntryTemplate} from './entry-templates';

// Public Booking galleries inspected on 2026-10-07. These are editable procedures,
// not claims about present dirt, occupancy or the date of the next cleaning.
const visit='Referência da estadia:\nHora limite para ficar pronto:\n\nUsar os produtos adequados a cada superfície e respeitar os rótulos; nunca misturar produtos. Separar panos da sanita, restantes zonas da casa de banho e cozinha/quartos. Não molhar equipamentos elétricos. Comunicar faltas, danos ou odores persistentes numa ocorrência com fotografia.';
const deepNote='Agendar com a casa livre e tempo para secar. Esta lista complementa as rotinas entre hóspedes. Ajustar a frequência à utilização e às etiquetas dos materiais.\n\n'+visit;
const task=(scope:typeof DUPLEX|typeof ALFAMA,id:string,label:string,hint:string,steps:string[],description=visit,category='Limpeza · Entre hóspedes'):EntryTemplate=>({id,kind:'task',scope,label,hint,steps,description,category});
const bedroomSteps=(two:boolean)=>[
 'Confirmar saída, ocupação seguinte e hora limite; arejar em segurança',
 'Recolher lixo, objetos esquecidos e roupa usada sem a sacudir; separar roupa limpa',
 ...(two?['Executar os passos seguintes nos dois quartos, incluindo as duas camas de casal']:[]),
 'Inspecionar colchão, protetor, almofadas e roupa de cama: manchas, humidade, pelos ou odores',
 'Retirar peças que precisem de lavagem ou substituição; comunicar sinais de pragas',
 'Limpar cabeceira, estrutura e pés da cama; aspirar tecido e costuras conforme o fabricante',
 'Limpar mesas de cabeceira, candeeiros, cómodas e gavetas vazias',
 'Limpar puxadores, interruptores, comandos e outros pontos de contacto',
 'Limpar TV, suporte acessível, espelhos e molduras com produto adequado',
 'Limpar armários e cabides disponíveis, incluindo superfícies superiores acessíveis',
 'Verificar cortinas, colcha, mantas e almofadas decorativas; retirar peças com manchas ou odor',
 'Limpar peitoris, puxadores e vidros interiores acessíveis; rever portadas e cantos',
 'Tirar o pó de objetos decorativos e das superfícies por baixo',
 'Aspirar rodapés, cantos e debaixo das camas e móveis acessíveis',
 'Limpar o soalho sem encharcar, conforme o acabamento; deixar secar',
 'Com mãos limpas, colocar lençóis e fronhas lavados e completamente secos',
 ...(two?['Verificar a primeira cama de casal: sem cabelos, manchas ou odor','Verificar a segunda cama de casal: sem cabelos, manchas ou odor']:['Rever a cama preparada: sem cabelos, manchas ou odor']),
 'Deixar apenas têxteis limpos e secos; preparar a roupa extra conforme a ocupação confirmada',
 'Repor consumíveis combinados e registar faltas, avarias ou peças retiradas'
];
const showerSteps=(duplex:boolean)=>[
 'Arejar em segurança e preparar panos exclusivos; retirar toalhas, tapete e lixo usados',
 'Retirar cabelos e resíduos da base de duche, lavatório e chão',
 'Limpar base de duche, rebordos e cantos, removendo restos de sabão',
 'Limpar ralo e tampa acessíveis; testar escoamento sem desmontar instalações',
 'Limpar chuveiro, mangueira, torneiras e suportes; tratar calcário com produto compatível',
 ...(duplex?['Limpar os dois lados do painel de vidro do duche, bordos e juntas']:['Limpar os dois lados das portas da cabine, puxadores, perfis e calhas acessíveis']),
 'Limpar azulejos e juntas na zona do duche, incluindo os cantos baixos',
 'Verificar silicone, fugas e bolor persistente; registar o que exige reparação',
 ...(duplex?['Limpar os dois lavatórios: interior, exterior, ralos e base das duas torneiras']:['Limpar lavatório, ralo, torneira e zona por trás da torneira']),
 'Limpar bancada, móvel ou prateleiras de apoio e puxadores; secar bem',
 ...(duplex?['Limpar os dois espelhos sem marcas e a estante de ripas por cima e por baixo']:['Limpar espelho, bordos e móvel do lavatório sem deixar dedadas']),
 'Limpar doseadores, bicos, copos, saboneteiras e suportes; repor conforme as instruções',
 'Limpar porta, puxador, interruptor e peitoril ou ventilação acessível',
 ...(duplex?['Limpar o bidé: torneira, interior, exterior, base e zona envolvente']:[]),
 'Com pano exclusivo, limpar sanita: tampa dos dois lados, assento, dobradiças e botão do autoclismo',
 'Limpar interior e rebordo da sanita, exterior, base e parte de trás',
 'Limpar escovilhão, suporte e caixote do lixo; substituir o que estiver degradado',
 'Após limpar, desinfetar os pontos previstos e respeitar o tempo indicado no rótulo',
 'Lavar chão e cantos, incluindo atrás da sanita; deixar completamente seco',
 'Com mãos limpas, colocar toalhas e tapete lavados e secos para a ocupação confirmada',
 'Repor papel higiénico, sabonete e saco do lixo',
 'Inspeção final: sem cabelos, calcário visível, sabão, odor ou água no chão'
];
const kitchenSteps=(duplex:boolean)=>[
 'Verificar frigorífico, armários e bancada; retirar alimentos deixados conforme a regra da casa',
 'Separar lixo e reciclagem; limpar caixotes, tampas, pedais e colocar sacos novos',
 'Lavar e secar loiça, copos, chávenas, talheres, panelas e utensílios usados',
 'Rever loiça arrumada: sem gordura, migalhas ou peças partidas',
 'Limpar bancada e azulejos ou painel de proteção, sobretudo junto à placa',
 'Limpar placa fria, comandos e zonas de gordura segundo o fabricante',
 'Limpar lava-loiça, torneira, escorredor e ralo acessível; retirar restos de comida',
 'Limpar portas e puxadores dos armários; rever gavetas dos talheres e cantos',
 'Limpar o frigorífico por dentro: prateleiras, gavetas, borrachas e puxador',
 'Limpar o micro-ondas se presente: prato, interior, porta e puxador; deixar seco',
 ...(duplex?['Rever o forno, se presente: tabuleiros, grelhas, interior e vidro; remover resíduos com o aparelho frio','Verificar máquina da loiça, se presente: retirar loiça limpa e limpar filtro acessível conforme o manual']:[]),
 'Esvaziar cápsulas e tabuleiro da máquina de café; lavar peças amovíveis conforme o fabricante',
 'Limpar chaleira e torradeira se presentes; retirar água antiga e migalhas em segurança',
 'Limpar o exterior do exaustor e a gordura acessível; agendar filtros quando necessário',
 'Limpar prateleiras abertas, recipientes e tabuleiros; retirar pó e migalhas',
 'Lavar mesa, individuais e cadeiras; secar superfícies que contactam com alimentos',
 'Substituir panos usados e esponjas degradadas; repor detergente e consumíveis combinados',
 'Aspirar e lavar o chão com material próprio; verificar debaixo dos móveis acessíveis',
 'Revisão final: sem gordura, restos, cheiros, louça suja ou água acumulada'
];
const finalSteps=(duplex:boolean)=>[
 'Confirmar ocupação, hora de chegada e necessidades de roupa de cama e toalhas',
 ...(duplex?['Rever os dois quartos e as duas camas; preparar sofá-cama apenas se necessário']:['Rever a cama do quarto e preparar o sofá-cama quando necessário']),
 'Verificar roupa de cama e toalhas: limpas, secas, sem cabelos ou manchas',
 'Rever duche, vidros, lavatórios, sanita e ralos: sem resíduos, odores ou fugas',
 'Confirmar loiça, bancada, frigorífico, caixotes e consumíveis prontos',
 'Rever sofá, debaixo dos móveis, peitoris, cantos e chão seco',
 ...(duplex?['Confirmar escadas e patamares secos, desimpedidos e bem iluminados']:['Confirmar passagem livre na sala e mesa recolhível estável']),
 'Testar luzes, comandos, Wi-Fi, água e acesso; comunicar qualquer avaria',
 'Deixar janelas e portas em posição segura e fotografar o resultado sem dados de hóspedes',
 'Só quando tudo estiver pronto, atualizar a limpeza na estadia para Concluída'
];

export const apartmentCleaningTemplates:EntryTemplate[]=[
 task(DUPLEX,'duplex-bedrooms','Dois quartos e camas','Entre hóspedes · duas camas de casal e roupa limpa.',bedroomSteps(true)),
 task(DUPLEX,'duplex-kitchen','Cozinha e equipamentos','Entre hóspedes · gordura, loiça, frigorífico e café.',kitchenSteps(true)),
 task(DUPLEX,'duplex-bathroom','Casa de banho e duche','Entre hóspedes · dois lavatórios, vidro, bidé e sanita.',showerSteps(true)),
 task(DUPLEX,'duplex-living','Sala, escadas e terraço','Entre hóspedes · sofá, cadeiras, degraus e exterior.',[
  'Recolher lixo e objetos esquecidos; verificar danos e faltas',
  'Aspirar sofá, braços, encosto, costuras, entre almofadas e por baixo',
  'Abrir o sofá-cama para verificar e aspirar o interior acessível; confirmar o mecanismo',
  'Retirar capas, mantas ou almofadas com manchas, pelos ou odor; lavar conforme a etiqueta',
  'Se o sofá-cama for utilizado, preparar roupa lavada e seca para a ocupação confirmada',
  'Limpar cadeiras de corda e respetivas estruturas, incluindo frestas e pés',
  'Limpar mesas de apoio e de jantar, cadeiras, candeeiros e elementos decorativos',
  'Limpar TV, comandos, interruptores e puxadores com produto adequado',
  'Limpar espelhos, peitoris, portas envidraçadas e vidros interiores acessíveis',
  'Limpar secretária e a zona acessível por baixo das escadas',
  'Aspirar cada degrau, canto e patamar; limpar corrimãos e guardas',
  'Limpar os degraus sem encharcar; manter a passagem impedida até estarem secos',
  'Verificar iluminação e firmeza do corrimão; comunicar danos',
  'No terraço em uso, recolher folhas e lixo; limpar cadeiras, mesa e chão com método adequado',
  'Limpar a guarda pelo lado seguro; observar ralos acessíveis sem trabalhos em altura',
  'Aspirar e limpar o soalho interior, rodapés e debaixo dos móveis acessíveis',
  'Deixar piso e escadas secos, passagem livre e portas/janelas em posição segura'
 ]),
 task(DUPLEX,'duplex-deep','Limpeza de detalhe','Agendar à parte · tecidos, cozinha e zonas escondidas.',[
  'Planear com a casa livre e tempo para secagem completa',
  'Lavar cortinas, colchas, mantas, capas e protetores conforme as etiquetas',
  'Rever edredões e almofadas dos dois quartos; encaminhar para lavagem adequada',
  'Aspirar colchões, cabeceiras estofadas e bases; inspecionar costuras e comunicar sinais de pragas',
  'Limpar a fundo o sofá e as cadeiras segundo os materiais; deixar secar totalmente',
  'Limpar atrás e por baixo de móveis que possam ser deslocados em segurança',
  'Limpar rodapés, portas, molduras, topos dos armários e cantos altos acessíveis',
  'Limpar cada recanto das escadas, guardas e zona por baixo; verificar fixações',
  'Limpar exaustor e filtros segundo o fabricante, com equipamento desligado',
  'Limpar a fundo forno, frigorífico e máquinas presentes, incluindo borrachas e filtros acessíveis',
  'Descalcificar máquina de café, chaleira e torneiras conforme os respetivos manuais',
  'Limpar grelhas e filtros acessíveis do ar condicionado conforme o manual, com o equipamento desligado',
  'Limpar juntas, bordos e silicone do duche; comunicar bolor persistente e fugas',
  'Limpar caixilhos e vidros interiores; tratar claraboia apenas com acesso seguro',
  'Rever o piso, mobiliário e escoamento do terraço; comunicar peças soltas ou degradadas',
  'Confirmar secagem, ausência de resíduos e registar reparações pendentes'
 ],deepNote,'Limpeza · A fundo'),
 task(DUPLEX,'duplex-ready','Revisão antes da chegada','Último olhar · quartos, cozinha, WC e escadas.',finalSteps(true),'Confirmar cada divisão antes de dar a casa como pronta. Corrigir ou reportar falhas; o estado de limpeza da estadia deve ser atualizado na própria reserva.','Limpeza · Revisão final'),
 task(ALFAMA,'alfama-bedroom','Quarto e roupa de cama','Entre hóspedes · cama, cabeceira, cortinas e soalho.',bedroomSteps(false)),
 task(ALFAMA,'alfama-kitchen','Kitchenette e loiça','Entre hóspedes · placa, micro-ondas, exaustor e frigorífico.',kitchenSteps(false)),
 task(ALFAMA,'alfama-bathroom','Casa de banho e cabine','Entre hóspedes · vidros, perfis, juntas e ralos.',showerSteps(false)),
 task(ALFAMA,'alfama-living','Sala e sofá-cama','Entre hóspedes · tecidos, mesa recolhível e passagem.',[
  'Recolher lixo e objetos esquecidos; fotografar danos ou faltas',
  'Retirar e verificar a capa ou manta do sofá; lavar conforme a etiqueta quando necessário',
  'Aspirar sofá, costuras, entre almofadas, estrutura e chão por baixo',
  'Abrir e inspecionar o sofá-cama; limpar o interior acessível e verificar o mecanismo',
  'Se necessário para a ocupação, fazer o sofá-cama com roupa lavada e completamente seca',
  'Rever almofadas e têxteis decorativos: sem manchas, pelos, cabelos ou odores',
  'Abrir a mesa recolhível e limpar tampos, laterais, articulações acessíveis e pés',
  'Limpar cadeiras e locais de arrumação; deixar a mesa estável na posição combinada',
  'Limpar TV, móvel de apoio, comandos, puxadores e interruptores',
  'Tirar o pó de candeeiros, molduras, decoração e radiador frio se presente',
  'Limpar peitoris, portadas e vidros interiores; observar a varanda pelo lado seguro',
  'Aspirar e limpar chão, rodapés e cantos sem encharcar a madeira',
  'Confirmar passagem livre até à porta, chão seco e ausência de resíduos da kitchenette',
  'Repor consumíveis combinados e registar avarias ou material em falta'
 ]),
 task(ALFAMA,'alfama-deep','Limpeza de detalhe','Agendar à parte · tecidos, cabine e kitchenette.',[
  'Planear com o alojamento livre e tempo para secagem completa',
  'Lavar cortinas, colcha, mantas, protetores e capas segundo as etiquetas',
  'Rever almofadas, edredão e capa do sofá; encaminhar para lavagem adequada',
  'Aspirar colchão, costuras e cabeceira; comunicar sinais de pragas ou contaminação',
  'Limpar o interior do sofá-cama e o chão atrás dos móveis que seja seguro deslocar',
  'Limpar a fundo as articulações acessíveis da mesa recolhível, cadeiras e rodapés',
  'Limpar exaustor e filtro conforme o fabricante, com equipamento desligado',
  'Limpar prateleiras abertas, armários, recipientes e zonas de gordura da kitchenette',
  'Limpar frigorífico e borrachas; descalcificar chaleira e máquina de café conforme o fabricante',
  'Limpar micro-ondas e restantes equipamentos presentes sem molhar partes elétricas',
  'Limpar cuidadosamente perfis, calhas, puxadores e cantos da cabine de duche',
  'Tratar resíduos nas juntas dos azulejos e verificar silicone; reportar degradação ou bolor persistente',
  'Rever ralos, escoamento e ventilação; comunicar odor persistente ou fugas',
  'Limpar caixilhos, portadas, peitoris e vidros interiores acessíveis sem se debruçar para o exterior',
  'Limpar cestos, objetos decorativos e zonas acessíveis atrás do radiador frio, se presente',
  'Rever todo o espaço à luz natural; confirmar secagem e registar reparações necessárias'
 ],deepNote,'Limpeza · A fundo'),
 task(ALFAMA,'alfama-ready','Revisão antes da chegada','Último olhar · quarto, sofá-cama, kitchenette e WC.',finalSteps(false),'Confirmar a cama e o sofá-cama conforme a ocupação. Corrigir ou reportar falhas; o estado de limpeza da estadia deve ser atualizado na própria reserva.','Limpeza · Revisão final')
];
