import type {EntryTemplate} from './entry-templates';

export const laundryProfile={
 name:'Lavadeira do Bairro',
 address:'Rua José Ricardo, 36 · Lisboa',
 summary:'Máquinas de lavar · Secadores · Central de pagamento',
 focus:'Cotão entre as máquinas e por cima dos secadores todas as semanas. Os filtros têm uma rotina própria, mais frequente.',
};

// Researched 2026-10-07. See docs/lavandaria-fontes.md for sources and limits.
// Exact makes/models are not confirmed. These are editable operating checklists,
// not model-specific service instructions or a diagnosis from online reviews.
const location='Lavadeira do Bairro · Rua José Ricardo, 36, Lisboa.';
const care='Usar os produtos e o método do manual de cada máquina. Aplicar produto no pano, não nos comandos; não usar jatos de água, abrasivos ou misturas de produtos. Limpar apenas zonas acessíveis ao operador. Manutenção interna e deslocação de máquinas são trabalho do técnico.';
const visit=`${location}\n\nMáquinas verificadas (identificação):\nFaltas ou anomalias:\n\n${care}`;

export const laundryTemplates:EntryTemplate[]=[
 {
  id:'laundry-clean',kind:'task',scope:'Lavandaria',label:'Limpeza do espaço',
  recordTitle:'Limpar a Lavadeira do Bairro',category:'Limpeza · Diária',repeat:'Diária',
  hint:'Diariamente · bancadas, assentos, vidros, lixo e chão.',description:visit,
  steps:[
   'Escolher um período calmo; sinalizar a zona de limpeza e manter a passagem livre',
   'Recolher lixo e identificar objetos esquecidos sem misturar com roupa dos clientes',
   'Esvaziar os caixotes, limpar tampa e pedal e colocar sacos novos',
   'Retirar pó e cotão das superfícies acessíveis, de cima para baixo',
   'Limpar e secar a mesa de dobrar roupa, incluindo bordos e parte inferior acessível',
   'Limpar assentos, encostos e apoios, com atenção às frestas',
   'Limpar puxadores, interruptores e exterior da central de pagamento com pano adequado',
   'Limpar vidros da entrada e portas, retirando marcas de dedos',
   'Aspirar cotão, cabelos e resíduos do chão, cantos e rodapés',
   'Lavar o chão por zonas e deixar secar antes de retirar a sinalização',
   'Confirmar que mesas e assentos estão secos e a circulação está desimpedida',
   'Registar faltas e problemas com fotografia, sem fotografar clientes ou os seus dados',
  ],
 },
 {
  id:'laundry-washers',kind:'task',scope:'Lavandaria',label:'Máquinas de lavar',
  recordTitle:'Limpar portas, borrachas e tambores das máquinas de lavar',category:'Limpeza · Diária',repeat:'Diária',
  hint:'Diariamente · portas, borrachas, resíduos, odores e fugas.',description:visit,
  steps:[
   'Identificar as máquinas disponíveis; esperar pelo fim dos ciclos e não retirar roupa dos clientes',
   'Colocar cada máquina fora de uso durante a limpeza e seguir o isolamento previsto no manual',
   'Verificar o tambor vazio e retirar cabelos, papel e objetos acessíveis, sem desmontar peças',
   'Limpar o vidro da porta por dentro e por fora com produto compatível',
   'Limpar suavemente a borracha e as suas dobras; procurar sujidade, cortes e objetos presos',
   'Limpar e secar o puxador, a frente e os comandos; não pulverizar diretamente',
   'Verificar gavetas acessíveis de detergente, se existirem; limpar apenas conforme o manual',
   'Observar resíduos, espuma persistente ou odor no tambor e registar a máquina afetada',
   'Procurar água no chão e fugas visíveis nas ligações, sem apertar ou desmontar',
   'Registar necessidade de ciclo de manutenção aprovado; não escolher químicos ou temperaturas ao acaso',
   'Confirmar superfícies secas e a máquina pronta; manter fora de serviço se houver avaria',
  ],
 },
 {
  id:'laundry-dryers',kind:'task',scope:'Lavandaria',label:'Secadores e filtros de cotão',
  recordTitle:'Verificar secadores e limpar filtros de cotão',category:'Limpeza · Secadores',repeat:'Diária',
  hint:'Verificação diária · filtros após cada carga se o manual o exigir.',
  description:`${visit}\n\nA tarefa diária é um registo de verificação. Não substitui a limpeza após cada carga quando exigida pelo fabricante. Confirmar a frequência e o acesso aos filtros no manual do modelo instalado. A limpeza semanal entre máquinas não substitui os filtros.`,
  steps:[
   'Identificar cada secador e confirmar no manual a frequência de limpeza do filtro',
   'Esperar pelo fim do ciclo e arrefecimento; não interromper uma carga quente para fazer a limpeza',
   'Impedir a utilização durante a intervenção e isolar o equipamento como indicado no manual',
   'Retirar apenas o filtro acessível ao operador, seguindo o procedimento do modelo',
   'Remover o cotão do filtro com o método aprovado; não rasgar a malha nem empurrar cotão para dentro',
   'Limpar o alojamento acessível do filtro conforme o manual, sem abrir painéis técnicos',
   'Verificar malha, encaixe e vedantes; registar rasgões ou peças soltas',
   'Recolocar o filtro limpo e bem encaixado; nunca disponibilizar o secador sem filtro',
   'Limpar porta, puxador, borracha e tambor vazio conforme o manual; deixar seco',
   'Verificar se as grelhas exteriores estão livres de cotão e objetos',
   'Registar secagem anormalmente lenta, ruído ou sobreaquecimento e retirar de serviço até avaliação',
   'Anotar os secadores verificados e as horas das limpezas de filtros realizadas nesta visita',
  ],
 },
 {
  id:'laundry-weekly-lint',kind:'task',scope:'Lavandaria',label:'Cotão entre máquinas e no topo',
  recordTitle:'Limpar cotão entre as máquinas e por cima dos secadores',category:'Limpeza · Semanal',repeat:'Semanal',
  hint:'Todas as semanas · intervalos, laterais, topos e rodapés.',
  description:`${location}\n\nRotina semanal pedida pela proprietária. Reforçar se o cotão se acumular antes. Fotografar as zonas antes/depois sem clientes. Se não for possível chegar em segurança, registar o ponto por limpar e pedir intervenção.\n\n${care}`,
  steps:[
   'Planear um período sem utilização da zona e sinalizar os equipamentos em limpeza',
   'Esperar pelo fim dos ciclos e arrefecimento; cumprir o isolamento indicado nos manuais',
   'Inspecionar o cotão entre cada par de máquinas, nas laterais e por cima de todos os secadores',
   'Usar aspirador e acessório comprido adequados para recolher o cotão acessível; não o soprar para dentro',
   'Aspirar entre as máquinas, de cima para baixo, sem puxar cabos ou tubos',
   'Limpar o topo exterior de cada secador com acessório extensível a partir do chão; não subir às máquinas',
   'Se o topo não for alcançável em segurança, registar para equipa com meios adequados; não improvisar apoios',
   'Limpar laterais, rebordos e juntas exteriores acessíveis com pano ligeiramente humedecido e secar',
   'Aspirar rodapés e o chão acessível por baixo e atrás, sem deslocar os equipamentos',
   'Retirar cotão das grelhas exteriores acessíveis sem abrir condutas, tampas ou painéis técnicos',
   'Esvaziar o reservatório do aspirador de acordo com o seu manual e retirar os resíduos do espaço',
   'Confirmar entradas de ar livres; registar acumulação recorrente ou zonas inacessíveis para o técnico',
   'Juntar fotografia do resultado e anotar o que ficou por resolver antes de concluir',
  ],
 },
 {
  id:'laundry-check',kind:'task',scope:'Lavandaria',label:'Verificação de funcionamento',
  recordTitle:'Verificar máquinas, pagamentos e instruções da lavandaria',category:'Operação · Diária',repeat:'Diária',
  hint:'Diariamente · erros, pagamentos, instruções e ajuda visível.',description:visit,
  steps:[
   'Registar as máquinas disponíveis e as que apresentam erro, pela sua identificação',
   'Confirmar que avarias estão sinalizadas e comunicadas ao responsável',
   'Verificar se o terminal está operacional e se existem pagamentos pendentes de esclarecimento',
   'Confirmar preços e métodos de pagamento afixados com a configuração atual, sem usar preços antigos da Internet',
   'Verificar instruções claras em português e inglês: máquina, programa, pagamento e início',
   'Confirmar que a informação sobre troco ou crédito corresponde ao funcionamento real do terminal',
   'Verificar capacidade máxima e orientação de secagem afixadas conforme cada máquina',
   'Confirmar que o contacto de apoio está legível e que os pedidos recebidos têm responsável',
   'Anotar filas, máquinas indisponíveis ou queixas repetidas para a gestão decidir melhorias',
  ],
 },
 {
  id:'laundry-stock',kind:'task',scope:'Lavandaria',label:'Stock e consumíveis',
  recordTitle:'Verificar e repor consumíveis da lavandaria',category:'Operação · Semanal',repeat:'Semanal',
  hint:'Semanalmente · stock, níveis, derrames e material de limpeza.',description:`${visit}\n\nProdutos e stock mínimo acordado:\nQuem pode repor o sistema de dosagem:`,
  steps:[
   'Contar detergentes, sacos, panos e restantes consumíveis; comparar com o mínimo acordado',
   'Verificar níveis visíveis e alarmes de dosagem, sem alterar parâmetros',
   'Verificar embalagens identificadas, tampas fechadas e sinais de derrame',
   'Repor apenas os produtos aprovados, por pessoa instruída e segundo o procedimento do sistema',
   'Não misturar produtos nem reutilizar embalagens sem identificação',
   'Registar produto, quantidade reposta, stock final e o que precisa de compra',
   'Confirmar aspirador, acessórios compridos e panos prontos para a limpeza do cotão',
  ],
 },
 {
  id:'laundry-monthly',kind:'task',scope:'Lavandaria',label:'Revisão de manutenção',
  recordTitle:'Rever manutenção e intervenções técnicas da lavandaria',category:'Manutenção · Mensal',repeat:'Mensal',
  hint:'Mensalmente · histórico, desgaste e próxima visita do técnico.',
  description:`${location}\n\nEsta revisão mensal é de acompanhamento. A manutenção técnica segue os intervalos de horas/ciclos e o manual do modelo. Abertura de painéis, condutas, motores e ligações elétricas ou de gás é reservada ao técnico habilitado.\n\nTécnico/contacto:\nÚltima visita:\nPróxima intervenção acordada:`,
  steps:[
   'Confirmar marca, modelo e número de identificação de cada máquina e guardar referência ao manual',
   'Rever ocorrências de fugas, ruído, erros, secagem lenta e reclamações por equipamento',
   'Verificar visualmente portas, borrachas e mangueiras acessíveis, sem desmontar ou intervir',
   'Confirmar o plano técnico para exaustão, condutas e acumulação interna de cotão conforme os manuais',
   'Confirmar com o técnico o plano de limpeza interna, descalcificação e dosagem das lavadoras',
   'Conferir a última assistência e os prazos por data, horas ou ciclos; marcar as intervenções em falta',
   'Guardar o contacto do técnico, orçamento e trabalhos executados no histórico da tarefa',
   'Criar ocorrências separadas para reparações que continuem pendentes',
  ],
 },
 {
  id:'laundry-service',kind:'task',scope:'Lavandaria',label:'Marcar assistência a uma máquina',
  hint:'Máquina, erro, técnico, orçamento e visita.',description:`${location}\n\nMáquina/modelo:\nCódigo de erro:\nTécnico/contacto:`,
  steps:['Identificar a máquina e descrever o problema','Juntar fotografia ou código de erro, sem abrir painéis','Contactar o técnico e registar a orientação recebida','Combinar a visita e obter orçamento para aprovação','Registar o trabalho efetuado e a confirmação de reposição em serviço'],
 },
 {
  id:'laundry-fault',kind:'incident',scope:'Lavandaria',label:'Máquina ou secador com problema',
  hint:'Equipamento, sintoma e fotografia para o responsável.',
  description:`${location}\n\nEquipamento / número:\nO que aconteceu:\nCódigo de erro:\nFicou fora de serviço?\nPessoa informada:`,
  steps:['Identificar a máquina e registar o sintoma observado','Sinalizar fora de serviço quando necessário e informar o responsável','Juntar fotografia segura e combinar o próximo passo'],
 },
 {
  id:'laundry-feedback',kind:'incident',scope:'Lavandaria',label:'Pedido ou reclamação de cliente',
  hint:'Lavagem, secagem, pagamento ou dificuldade de utilização.',
  recordTitle:'',category:'Apoio ao cliente',
  description:`${location}\n\nData e hora:\nMáquina / programa:\nRelato do cliente (por confirmar):\nValor / referência do pagamento, se relevante:\nContacto fornecido pelo cliente:\nResposta ou solução acordada:\nQuem acompanha e até quando:`,
  steps:['Registar o relato e a máquina sem assumir a causa','Verificar o ocorrido com o responsável, preservando os dados do cliente','Propor solução para aprovação; registar resposta e fecho'],
 },
 {
  id:'laundry-buy',kind:'purchase',scope:'Lavandaria',label:'Detergente e consumíveis',
  hint:'Produto aprovado, quantidade e stock disponível.',category:'Consumíveis da lavandaria',
  description:`${location}\n\nProduto aprovado / referência:\nQuantidade necessária:\nStock atual:\nData em que será necessário:`,
 },
];
