import {z} from 'zod';
export const areas=['Família','Casa','Quinta · Arruda','Lavandaria','Alojamento 1','Alojamento 2','Alojamento 3'] as const;
export const states=['Por fazer','Em curso','À espera','Por aprovar','Aprovado','Concluído','Cancelado'] as const;
export const kinds=['task','incident','purchase','supplier','stay'] as const;
export const recordSchema=z.object({nextStep:z.string().max(300).default(''),steps:z.array(z.object({id:z.string().max(100),title:z.string().trim().min(1).max(200),done:z.boolean()})).max(30).default([]),waitingFor:z.string().max(150).default(''),reviewOn:z.string().max(10).default(''),snoozeUntil:z.string().max(10).default(''),title:z.string().trim().min(2).max(160),area:z.enum(areas),description:z.string().max(5000).default(''),status:z.enum(states).default('Por fazer'),priority:z.enum(['Normal','Alta','Urgente']).default('Normal'),assignee:z.string().max(150).default('Por atribuir'),due:z.string().max(16).default(''),time:z.string().max(5).default(''),repeat:z.enum(['Não repetir','Semanal','Mensal']).default('Não repetir'),accepted:z.boolean().default(false),price:z.number().min(0).max(1000000).nullable().default(null),url:z.string().max(2000).refine(v=>!v||/^https?:\/\//.test(v),'Use um endereço https://').default(''),supplierId:z.string().max(100).default(''),phone:z.string().max(40).regex(/^[+\d\s().-]*$/,'Telefone inválido').default(''),email:z.union([z.literal(''),z.string().email().max(200)]).default(''),serviceAreas:z.array(z.enum(areas)).max(7).default([]),completedAt:z.string().default(''),contact:z.string().max(200).default(''),category:z.string().max(100).default(''),channel:z.enum(['Manual','Booking','Airbnb','Trip.com','Talkguest']).default('Manual'),checkout:z.string().max(10).default(''),guests:z.number().int().min(1).max(100).default(1),confirmedGuests:z.number().int().min(1).max(100).nullable().default(null),guestsConfirmed:z.boolean().default(false),arrival:z.string().max(5).default(''),arrivalConfirmed:z.boolean().default(false),cleaning:z.enum(['Por marcar','Marcada','Concluída']).default('Por marcar'),quotes:z.array(z.object({id:z.string(),supplier:z.string().min(1).max(160),amount:z.number().min(0).max(1000000),notes:z.string().max(1000),url:z.string().max(2000).refine(v=>!v||/^https?:\/\//.test(v)),selected:z.boolean()})).max(30).default([])});
export type Data=z.infer<typeof recordSchema>;
export type Item={id:string;kind:typeof kinds[number];data:Data;version:number;updated_at:string;created_by:string};
export function maySee(item:Item,member:{role:string;name:string;email:string}) {return member.role==='admin'||(['task','incident'].includes(item.kind)&&item.data.area!=='Família'&&(item.data.assignee===member.name||item.created_by===member.email));}
export function notices(items:Item[],today:string){return items.filter(i=>i.kind!=='supplier'&&!['Concluído','Cancelado'].includes(i.data.status)).flatMap(i=>{const d=i.data;const out:{id:string;title:string;reason:string}[]=[];if(d.snoozeUntil&&d.snoozeUntil<=today)out.push({id:i.id,title:d.title,reason:'Retomar assunto adiado'});if(d.reviewOn&&d.reviewOn<=today&&d.status==='À espera')out.push({id:i.id,title:d.title,reason:'Voltar a contactar '+(d.waitingFor||'o responsável')});if(d.due&&d.due<today)out.push({id:i.id,title:d.title,reason:'Prazo ultrapassado'});if(d.status==='Por aprovar')out.push({id:i.id,title:d.title,reason:'Precisa da tua decisão'});if(i.kind==='task'&&d.assignee==='Por atribuir')out.push({id:i.id,title:d.title,reason:'Falta atribuir um responsável'});if(i.kind==='stay'){if(!d.guestsConfirmed)out.push({id:i.id,title:d.title,reason:'Confirmar o número de hóspedes'});if(!d.arrivalConfirmed)out.push({id:i.id,title:d.title,reason:'Confirmar a hora de chegada'});if(d.guestsConfirmed&&d.confirmedGuests!==d.guests)out.push({id:i.id,title:d.title,reason:'Ocupação diferente da reserva'});if(d.cleaning==='Por marcar')out.push({id:i.id,title:d.title,reason:'Limpeza por marcar'});}return out;});}
