import {cookies} from 'next/headers';
import {database} from './supabase-database';
export {config,rest} from './backend';
import {config} from './backend';
export function db(){return database();}
export async function authRequest(path:string,body:unknown){const e=config();return fetch(e.SUPABASE_URL+'/auth/v1/'+path,{method:'POST',headers:{apikey:e.SUPABASE_PUBLISHABLE_KEY,'Content-Type':'application/json'},body:JSON.stringify(body)});}
export async function setSession(s:any){const c=await cookies();const opts={httpOnly:true,secure:true,sameSite:'lax' as const,path:'/'};c.set('ced-access',s.access_token,{...opts,maxAge:s.expires_in||3600});c.set('ced-refresh',s.refresh_token,{...opts,maxAge:60*60*24*30});}
export async function member(){const e=config(),c=await cookies();const token=c.get('ced-access')?.value;const getUser=async(t:string)=>fetch(e.SUPABASE_URL+'/auth/v1/user',{headers:{apikey:e.SUPABASE_PUBLISHABLE_KEY,Authorization:'Bearer '+t}});let r=token?await getUser(token):null;if((!r||r.status===401)&&c.get('ced-refresh')?.value){const rr=await authRequest('token?grant_type=refresh_token',{refresh_token:c.get('ced-refresh')!.value});if(rr.ok){const s:any=await rr.json();await setSession(s);r=await getUser(s.access_token);}}
if(!r||r.status===401)throw new Response('Inicia sessão para continuar.',{status:401});if(!r.ok)throw new Error('Auth unavailable');const u:any=await r.json();if(!u.email||!u.email_confirmed_at)throw new Response('Confirma o teu email.',{status:401});const m=await db().prepare('SELECT * FROM members WHERE email=?').bind(u.email.toLowerCase()).first<any>();if(!m||m.active===false)throw new Response('O teu acesso ainda não foi autorizado pela responsável.',{status:403});return m;}
export function bucket(){return {async get(id:string){const e=config();const r=await fetch(e.SUPABASE_URL+'/storage/v1/object/casa-em-dia/'+encodeURIComponent(id),{headers:{apikey:e.SUPABASE_SECRET_KEY,Authorization:'Bearer '+e.SUPABASE_SECRET_KEY}});if(r.status===404)return null;if(!r.ok)throw new Error('Storage unavailable');return {body:r.body};},async put(id:string,data:ArrayBuffer,opts:any){const e=config();const r=await fetch(e.SUPABASE_URL+'/storage/v1/object/casa-em-dia/'+encodeURIComponent(id),{method:'POST',headers:{apikey:e.SUPABASE_SECRET_KEY,Authorization:'Bearer '+e.SUPABASE_SECRET_KEY,'Content-Type':opts.httpMetadata.contentType},body:data});if(!r.ok)throw new Error('Upload failed');},async delete(id:string){const e=config();const r=await fetch(e.SUPABASE_URL+'/storage/v1/object/casa-em-dia',{method:'DELETE',headers:{apikey:e.SUPABASE_SECRET_KEY,Authorization:'Bearer '+e.SUPABASE_SECRET_KEY,'Content-Type':'application/json'},body:JSON.stringify({prefixes:[id]})});if(!r.ok)throw new Error('Storage cleanup failed');}};}
export function sameOrigin(r:Request){const o=r.headers.get('origin');if(o&&o!==new URL(r.url).origin)throw new Response('Pedido não autorizado',{status:403});}
export function fail(e:unknown){if(e instanceof Response)return e;console.error('Casa em Dia: operação indisponível');return Response.json({error:'Não foi possível guardar ou carregar os dados. Tenta novamente.'},{status:503});}
export function json(v:unknown){return Response.json(v,{headers:{'Cache-Control':'no-store'}});}
