import {db,member,sameOrigin,fail,json} from '@/lib/server';
import {recordSchema,kinds,maySee,canTrash} from '@/lib/model';
export async function GET(r:Request){try{const m=await member();const d=db();const rows=await d.prepare('SELECT * FROM records ORDER BY updated_at DESC LIMIT 2000').all<any>();const items=rows.results.map(x=>({...x,data:recordSchema.parse(JSON.parse(x.data))})).filter(x=>maySee(x,m));const id=new URL(r.url).searchParams.get('id');if(id){if(!items.some(x=>x.id===id&&!x.data.deletedAt))return new Response('Sem acesso',{status:404});const [f,a]=await Promise.all([d.prepare('SELECT * FROM files WHERE record_id=?').bind(id).all(),d.prepare('SELECT * FROM audit WHERE record_id=? ORDER BY at DESC LIMIT 50').bind(id).all()]);return json({files:f.results,audit:a.results});}const team=await d.prepare('SELECT name,email,role FROM members').all();return json({items:items.filter(i=>!i.data.deletedAt),deletedItems:items.filter(i=>i.data.deletedAt&&canTrash(i,m)),member:m,team:m.role==='admin'?team.results:[m]});}catch(e){return fail(e);}}
export async function POST(r:Request){try{sameOrigin(r);const m=await member();if(Number(r.headers.get('content-length')||0)>50000)return new Response('Pedido demasiado grande',{status:413});const p=await r.json() as any;if(!kinds.includes(p.kind))return new Response('Tipo inválido',{status:400});const parsed=recordSchema.safeParse(p.data);if(!parsed.success)return Response.json({error:'Verifica os campos: '+parsed.error.issues.map(x=>x.path.join('.')+' '+x.message).join('; ')},{status:400});const data=parsed.data;const dateOk=(s:string)=>!s||/^\d{4}-\d{2}-\d{2}$/.test(s)&&!isNaN(Date.parse(s));const timeOk=(s:string)=>!s||/^([01]\d|2[0-3]):[0-5]\d$/.test(s);if(!dateOk(data.reviewOn)||!dateOk(data.snoozeUntil)||!dateOk(data.due)||!dateOk(data.checkout)||!timeOk(data.time)||!timeOk(data.arrival))return new Response('Data ou hora inválida',{status:400});if(p.kind==='stay'&&(!data.due||!data.checkout||data.checkout<=data.due||!data.area.startsWith('Alojamento')||(data.arrivalConfirmed&&!data.arrival)||(data.guestsConfirmed&&!data.confirmedGuests)))return new Response('Verifica datas, hóspedes e hora da estadia.',{status:400});const d=db();const old=p.id?await d.prepare('SELECT * FROM records WHERE id=?').bind(p.id).first<any>():null;if(p.id&&!old)return new Response('Registo não encontrado',{status:404});const previous=old?{...old,data:JSON.parse(old.data)}:null;if(previous&&(!maySee(previous,m)||previous.kind!==p.kind))return new Response('Sem acesso',{status:403});if(previous?.data.deletedAt)return new Response('Esta tarefa está no lixo. Recupera-a antes de editar.',{status:409});data.deletedAt='';if(m.role!=='admin'){if(!['task','incident'].includes(p.kind)||data.area==='Família'||data.status==='Aprovado')return new Response('Sem permissão',{status:403});data.assignee=m.name;data.quotes=previous?.data.quotes||[];data.price=previous?.data.price??null;data.supplierId=previous?.data.supplierId||'';}
if(m.role==='admin'&&data.supplierId){const supplier=await d.prepare('SELECT * FROM records WHERE id=?').bind(data.supplierId).first<any>();if(!supplier||supplier.kind!=='supplier'||p.kind==='supplier')return new Response('Escolhe um contacto válido.',{status:400});}
data.completedAt=data.status==='Concluído'?(previous?.data.status==='Concluído'?(previous.data.completedAt||old.updated_at):new Date().toISOString()):'';
const id=old?.id||crypto.randomUUID(),at=new Date().toISOString();if(old){const res=await d.prepare('UPDATE records SET data=?,updated_at=?,version=version+1 WHERE id=? AND version=?').bind(JSON.stringify(data),at,id,p.version).run();if(!res.meta.changes)return new Response('Outra pessoa alterou este registo. Fecha e abre novamente antes de guardar.',{status:409});}else await d.prepare('INSERT INTO records(id,kind,data,created_by,updated_at,version) VALUES (?,?,?,?,?,1)').bind(id,p.kind,JSON.stringify(data),m.email,at).run();await d.prepare('INSERT INTO audit(id,record_id,actor,action,at) VALUES (?,?,?,?,?)').bind(crypto.randomUUID(),id,m.name,old?`Atualizado · ${data.status}`:'Registo criado',at).run();
if(old&&previous.data.status!=='Concluído'&&data.status==='Concluído'&&data.repeat!=='Não repetir'&&data.due){const next={...data,status:'Por fazer',accepted:false,completedAt:'',price:null,snoozeUntil:'',reviewOn:'',waitingFor:'',steps:data.steps.map(s=>({...s,done:false}))};const dt=new Date(data.due+'T12:00:00Z');if(data.repeat==='Semanal')dt.setUTCDate(dt.getUTCDate()+7);else{const day=dt.getUTCDate();dt.setUTCDate(1);dt.setUTCMonth(dt.getUTCMonth()+1);const last=new Date(Date.UTC(dt.getUTCFullYear(),dt.getUTCMonth()+1,0)).getUTCDate();dt.setUTCDate(Math.min(day,last));}next.due=dt.toISOString().slice(0,10);await d.prepare('INSERT INTO records(id,kind,data,created_by,updated_at,version) VALUES (?,?,?,?,?,1)').bind(crypto.randomUUID(),p.kind,JSON.stringify(next),m.email,at).run();}return json({id});}catch(e){return fail(e);}}

async function changeTrash(r:Request,restore:boolean){
 try{
  sameOrigin(r);const m=await member();const p=await r.json() as any;
  if(typeof p.id!=='string'||p.id.length>100||!Number.isInteger(p.version)||p.version<1||(restore&&p.action!=='restore'))return new Response('Pedido inválido.',{status:400});
  const d=db(),old=await d.prepare('SELECT * FROM records WHERE id=?').bind(p.id).first<any>();
  if(!old)return new Response('Tarefa não encontrada.',{status:404});
  const item={...old,data:recordSchema.parse(JSON.parse(old.data))};
  if(!canTrash(item,m))return new Response('Não tens permissão para apagar ou recuperar esta tarefa.',{status:403});
  if(Boolean(item.data.deletedAt)!==restore)return new Response(restore?'A tarefa já foi recuperada.':'A tarefa já está no lixo.',{status:409});
  const at=new Date().toISOString(),data={...item.data,deletedAt:restore?'':at};
  const result=await d.prepare('UPDATE records SET data=?,updated_at=?,version=version+1 WHERE id=? AND version=?').bind(JSON.stringify(data),at,p.id,p.version).run();
  if(!result.meta.changes)return new Response('A tarefa foi alterada por outra pessoa. Atualiza a lista e tenta novamente.',{status:409});
  await d.prepare('INSERT INTO audit(id,record_id,actor,action,at) VALUES (?,?,?,?,?)').bind(crypto.randomUUID(),p.id,m.name,restore?'Tarefa recuperada':'Tarefa movida para o lixo',at).run();
  return json({id:p.id,version:p.version+1});
 }catch(e){return fail(e);}
}
export const DELETE=(r:Request)=>changeTrash(r,false);
export const PATCH=(r:Request)=>changeTrash(r,true);
